
/* ==========================================================================
   LES GENS
   ========================================================================== */

const GENS = [
{ id:`andrew`, nom:`Andrew`, voie:`andrew`, role:`Le veilleur. Protagoniste.`,
  age:`Arrivé à 62 ans — son âge de mort. 52 ans au début du roman, 46 à l'épilogue.`,
  resume:`Dix ans dans ce monde, plusieurs années de service : ni débutant, ni vétéran. Il sait faire, et il ne sait rien de l'histoire de son métier. Il est porteur de voiles et personne ne le sait, lui non plus. Ce qu'il veut, il ne peut pas le formuler : il reçoit un arrivant de dix ans à une cérémonie ordinaire, quelque chose l'accroche malgré lui, et il retourne le voir sans mandat, sans mission, sans savoir pourquoi.`,
  traits:[`Fin observateur — c'est le seul trait de métier qu'on lui connaisse, et il ne s'en sert qu'à noter des chiffres.`,
    `Il demande son nom à un arrivant des dizaines de fois sans jamais se demander d'où vient le mot.`,
    `Il se sent chez lui dans un poste de police sans que rien ne l'explique.`,
    `Il sait à vue, sans compter, à quoi ressemble une arrivée de dix-huit ans au bout de dix ans — et il ne pose jamais l'opération.`,
    `Son apparence de cinquantenaire le désigne comme un arrivant encore récent : l'ancienneté et la jeunesse vont ensemble.`],
  faille:`Il fait confiance au document, pas à la personne. Il sur-lit une ligne de registre qui s'arrête, et il sous-lit un jeune arrivant qui lui parle. Le registre ne l'a jamais déçu, les gens si. C'est exactement la faute de Joël, qui a obéi à une procédure au lieu de suivre son affaire — le même homme, deux fois, et le même geste.`,
  arc:`Il retourne voir le garçon de lui-même, deux fois ; à la troisième il n'est plus là. On lui dit de lâcher l'affaire ; cette fois il refuse, et c'est le même examen repassé sans qu'il sache qu'il le repasse. Il continue seul, il trouve, et le garçon est vivant. Il remonte ensuite jusqu'à sa faute, va demander pardon à deux jeunes filles qui ne comprennent rien, et n'obtient rien.`,
  gardes:[`Aucune phrase ne justifie ses visites — ni du narrateur, ni de lui, ni d'un tiers.`,
    `Il ne comprend jamais. Pas d'illumination, pas même atténuée : « il chasse l'idée », « quelque chose lui échappe » sont faux.`,
    `Il n'apprend jamais qu'il s'est appelé Joël. Le nom d'avant n'existe que pour le lecteur.`,
    `Il ne calcule jamais un âge à voix haute ni dans sa tête.`,
    `Il ne retourne jamais au registre pour chercher qui d'autre est arrivé le jour d'Eliott.`,
    `Rien de sa mort passée ne doit ressembler à un sacrifice.`,
    `On ne commente jamais qu'il se sente chez lui au poste. Pas de « il se sentait étrangement à sa place ici ».`],
  portrait:[`**Grand sans etre imposant**, silhouette solide et equilibree, epaules larges, taille droite, bras fermes. *Le physique d'un homme qui entretient sa condition sans chercher a paraitre plus fort qu'il ne l'est.*`,
    `**Cheveux bruns, courts, legerement desordonnes** - quelques meches refusant de rester en place, **quelques autres restees blanches.** *Le seul mot qui porte le systeme est <em>restees</em>, et il ne s'explique pas.* Barbe courte, machoire carree, nez droit, sourcils epais, bouche expressive.`,
    `**Yeux d'un brun profond, attentifs**, toujours en train d'observer. *Chaleureux quand il se detend, nettement plus serieux des qu'il se concentre.* **Rien d'intimidant au premier regard, et pourtant il vaut mieux ne pas le sous-estimer.**`,
    `**Cinquante-deux ans. Dix ans de service.** ⛔ *Et la regle du monde ne s'explique jamais dans sa description* - decision de l'autrice, 19 aout 2026 : trop frontal. L'inversion des ages se posera ailleurs, dans un lieu ou dans une visite.`,
    `**La tenue :** blouse de toile ecrue, croisee sur le devant, six boutons sur le cote droit, l'ecusson brode sur l'epaule opposee, deux poches basses. **La ceinture au septieme trou en partant de l'extremite.** *Le petit clic, toujours au meme endroit. Pas six, pas huit. Sept.*`,
    `**Ses chaussures sont la seule chose a lui**, usees comme celles d'un homme qui traverse sa ville a pied tous les jours. **Quatre cent trente-huit** - le nombre de pas qui separent la ruche de son logement.`,
    `✅ **La manie ne se nomme jamais dans le portrait : elle se compte.** *Cinquante-deux, dix, six, deux, sept, quatre cent trente-huit.* **Personne ne dit qu'il compte ; on lit la description d'un homme qui compte.**`],
  phrases:[`C'est déjà ce qu'on m'a dit.`,`J'aurais dû continuer.`,`C'était là sous nos yeux.`],
  ouvert:[`Ce qui l'accroche chez Eliott, précisément — ou s'il n'y a rien à montrer.`,`✅ **Sa manie : il compte.** *Plantée en page une, 18 août 2026* — vingt-deux chaises empilées qu'il n'a pas décidé de compter, dix-sept visiteurs, sept éléments sur la table. **Et à la dernière page du livre :** *« il compta les petits en traversant. Ils étaient quarante-deux ».*`,`⛔ **La piste « il ne se souvient plus des cérémonies » était fausse et elle est retirée.** *Correction de l'autrice, 19 août 2026.* **C'est l'inverse : il est très physionomiste et il se souvient de ses cérémonies** — au chapitre premier il reconnaît un préparateur qu'il a relevé lui-même, et la formule qu'il a prononcée ce jour-là lui remonte entière. *« se souvint Andrew en considérant son sourire béat »*\n\n**Le seul trou est dans sa propre cérémonie**, et il n'a rien d'une honte : *comme tout arrivant il était dans le coltard, et il n'en a gardé que des morceaux.* **C'est au reveal qu'il raccroche tous les wagons.**`,`Réagit-il visiblement à la phrase du sentiment, à l'épilogue ?`],
  src:`03-personnages/andrew.md` },

{ id:`joel`, nom:`Joël`, voie:`joel`, role:`L'enquêteur qu'Andrew a été. La vie d'avant.`,
  age:`Mort à 62 ans, sur l'affaire des jumelles. C'est cet âge-là qu'il rapporte à sa capsule.`,
  resume:`Il travaille sur la disparition de deux sœurs jumelles ; l'étau se resserre sur un seul homme. Au milieu de l'enquête, on lui dit d'arrêter de creuser et il obéit — il perd des semaines. Il reprend, trouve la planque, et les filles sont mortes depuis moins d'une heure. Devant les corps, la culpabilité se retourne en rage en quelques secondes.`,
  traits:[`Il obéit à une consigne sans discuter, et c'est ce qui le perd.`,
    `Devant les corps, ce n'est pas de la tristesse mais un compte qui tombe — des jours identifiables, des heures pendant lesquelles il faisait autre chose.`,
    `Il laisse ses collègues sur place et ne se retourne pas quand on le rappelle.`,
    `Un taureau qui voit rouge, et c'est la seule fois du livre où il n'est plus lui-même.`],
  faille:`La même qu'Andrew, à l'inverse : aucune mesure. Il obéit quand il ne fallait pas, puis il n'obéit plus à rien, pas même à lui-même — et c'est la seconde qui le tue.`,
  arc:`Il cesse de chercher, il reprend, il arrive une heure trop tard, il part pour tuer, et il meurt. Le système ne juge pas les intentions : il n'a tué personne, il revient donc à soixante-deux ans, dossier ordinaire. Sa mort n'est pas la sanction de sa faute : c'est sa faute vue de l'autre côté.`,
  gardes:[`Il n'est nommé par personne dans tous les chapitres de la vie d'avant. On dit l'enquêteur, il, l'homme. Sauf une fois.`,
    `Aucun autre nom n'est prononcé dans ces chapitres — les deux filles n'en ont donc aucun.`,
    `Il ne meurt pas en sauvant quelqu'un. Sa poursuite ne sert à rien, personne ne la lui demande, aucun personnage ne commente sa mort.`,
    `La scène où on lui dit de lâcher l'affaire est la sienne, et le lecteur croit qu'elle est celle d'Andrew. Le chapitre d'avant est bien d'Andrew ; celui-ci ne l'est pas, et rien ne le signale.`],
  portrait:[`✅ **Le meme portrait qu'Andrew, a une chose pres : les marques.** *Quelques cicatrices discretes se devinent sur ses mains et pres de son sourcil, sans qu'il semble leur accorder la moindre importance.* **Elles font simplement partie de lui.**`,
    `**Et le lecteur ne peut pas s'en servir.** *Il n'a aucune raison de rapprocher un enqueteur marque d'un veilleur qui ne l'est pas.* **C'est seulement au bout qu'il comprend que l'un est la version lavee de l'autre.**`],
  phrases:[`Joël, non, attends !`,`On m'avait dit de laisser tomber, et je l'ai fait.`],
  ouvert:[`Pourquoi il reprend l'enquête — de lui-même, ou parce qu'un élément est ressorti. Le livre n'a pas besoin de trancher.`],
  src:`03-personnages/andrew.md` },

{ id:`eliott`, nom:`Eliott`, voie:`andrew`, role:`L'arrivant de dix ans. Le second et dernier porteur de voiles du livre.`,
  age:`Dix ans du début à la fin du corps du roman. Huit ans à l'épilogue, six ans plus tard.`,
  resume:`Il sort de sa capsule en parlant, comme tout le monde, et ce qu'il dit ne va pas : il est comme empreint d'une terreur qu'on ne comprend pas, et on passe outre. Tout le monde le prend pour un fabulateur. Ce qu'il porte, c'est une faute qui n'en est pas une : dans la vie d'avant il est tombé à l'eau, le courant l'a emporté, et quelqu'un s'est noyé en venant le chercher. Il ne sait rien de tout cela ; il a un sentiment énorme et pas un seul mot où le ranger.`,
  traits:[`Il parle d'emblée, et ce qu'il dit ne va pas.`,
    `Peur bleue de l'eau, colère noire au premier cours de natation.`,
    `Il boude dans un coin quand personne ne le croit — et ça le blesse énormément.`,
    `Il dévisage deux secondes l'arrivant de quarante ans, à la cérémonie. Quelque chose se ferme, il enchaîne.`,
    `Il raconte comme un enfant raconte : concrètement, dans le désordre, sans hiérarchie. C'est le calme qui glace.`,
    `Il part avec quelqu'un qu'il connaissait, sans se retourner.`],
  faille:`La culpabilité du survivant, qui n'a aucun fondement. Il porte une faute qui n'en est pas une, et il n'a ni les mots ni la notion de ce qu'il porte.`,
  arc:`Il arrive, il fabule, personne ne l'écoute. Il est enlevé par une berceuse qu'il croisait. Il est retrouvé vivant, deux semaines plus tard. Six ans après, à huit ans, il raconte l'eau et le sentiment juste avant d'entrer au jardin, personne ne comprend, et on l'emmène.`,
  portrait:[`**Donné par l'autrice le 22 août 2026, et transposé.** *Son texte disait <em>l'enfance</em>, <em>les enfants de son âge</em>, <em>un adolescent</em>, <em>en grandissant</em> — quatre mots que cette langue n'a pas.*`,
    `**Le visage doux, encore rond aux joues.** *Un nez court et droit, une bouche fine. Des cheveux bruns, épais, coupés par quelqu'un qui savait le faire et qui repartent en mèches sur le front et les oreilles.* **Ce qui tient le visage, ce sont les yeux : verts, grands, et ils lui donnent une présence que le reste n'annonce pas.** *Décision de l'autrice, 22 août 2026.* ⛔ *Première version : « verts, larges, et ils prenaient toute la place » — elle rendait le garçon inquiétant au lieu de le rendre présent.*`,
    `**Mince sans être maigre.** *Épaules étroites, poignets étroits, des mains encore petites.* **Et dans sa façon de se tenir, quelque chose qui cherche encore sa forme.**`,
    `🔴 **La tournure que l'autrice cherchait n'existe pas, et c'est tant mieux.** *Elle voulait remplacer <em>la forme qu'il prendrait en grandissant</em>.* ⛔ **Andrew ne peut pas avoir cette pensée :** *dans son monde, personne ne grandit — les corps descendent.* **On écrit donc la maladresse sans sa direction, et le lecteur fournit <em>il grandit</em> tout seul.** *Il a tort, et il ne le saura qu'à la fin.*`,
    `**Il regarde mieux qu'il n'en a l'air.** *Andrew l'a déjà vu à la cérémonie, sous la serviette — et c'est ce qu'il n'a pas écrit dans la case.*`],
  gardes:[`Rien de ce qu'il dit ne doit être vérifiable ni se recouper avec ce qui remonte chez Andrew. Banal, local, insignifiant — jamais un monument.`,
    `Sa terreur ne s'explique pas, ne se commente pas, et ne revient pas comme motif.`,
    `Les scènes de visite ne s'écrivent jamais comme des auditions.`,
    `Il ne dira jamais « papa » ni « père » ni aucun mot de parenté. Ils n'existent pas dans sa langue et il ne les cherche même pas.`,
    `Aucune phrase n'explique sa réplique finale. Ni personnage qui s'étonne, ni narrateur qui souligne qu'il manque un mot.`,
    `Son entrée au jardin n'est ni une mort ni une perte de la parole. Personne ne lui dit dans quoi il entre.`],
  phrases:[`Mais si, il y avait un boulanger ici, pas un magasin de chaussures.`,
    `Il m'aimait beaucoup, un sentiment fort, très fort. J'avais l'impression qu'il était moi et que moi j'étais lui. Comme si je l'aimais encore plus fort que lui !`],
  ouvert:[`Combien de visites exactement, et ce qu'il dit pendant.`,`Ce qu'il a dit exactement qui relance Andrew — le dernier trou du parcours.`,`Passait-il devant chez la ravisseuse sur sa tournée ? Lui a-t-il donné son nom ?`,`Qui est présent à l'épilogue.`],
  src:`03-personnages/eliott.md` },

{ id:`june`, nom:`June`, voie:`andrew`, role:`Berceuse. Celle qui a la charge d'Eliott.`,
  age:`**Environ vingt-deux ans** — décision de l'autrice, 16 août 2026. *C'est un âge apparent, et il ne dit rien de son ancienneté :* **elle a pu arriver à soixante ans, à quatre-vingts, à cent deux.** Ce qu'il dit, c'est ce qu'il lui reste — un berceur exerce jusqu'à douze ans, donc elle a encore quelques années devant elle. À l'épilogue elle a rajeuni, et il lui en reste toujours avant d'entrer au jardin à son tour.`,
  resume:`Elle exerce le métier qui accompagne jusqu'au dernier jour, auprès d'arrivants de tous les âges du jardin. C'est elle qu'on appelle pour nommer les arrivants de huit ans et moins, mais Eliott est arrivé à dix : elle ne l'a pas nommé, elle arrive après le registre. **Elle en a trois à charge — Paul, Julie, et Eliott le dernier arrivé.** Elle héberge les visites d'Andrew sans les trouver remarquables, cherche l'enfant quand il disparaît, prévient la police dans l'ordre, et le lui apprend parce qu'il faut bien que quelqu'un le dise.`,
  traits:[`Elle ouvre, elle laisse parler, elle n'assiste pas forcément.`,
    `Elle est la mémoire de ce que le petit racontait, et le restitue sans y rien ajouter.`,
    `Elle est dans la confidence des pédiatres du jardin et connaît, pour chaque enfant dont elle a la charge, la date où la descente a commencé.`,
    `Elle se tait par métier, et c'est la seule personne pour qui ce silence est une habitude.`,
    `Dépassée, elle laisse une demi-phrase en suspens puis passe à autre chose.`],
  faille:`Son métier lui demande de détenir un savoir et de ne jamais le rendre à l'intéressé. Elle n'est pas une menteuse : elle n'a jamais eu à se demander si c'était bien. C'est le seul endroit du monde où quelqu'un sait et garde.`,
  arc:`Trois gestes pendant l'enquête, et aucun ne déclenche quoi que ce soit : elle héberge, elle constate et prévient, elle annonce. **Puis elle garde Eliott six ans**, de dix ans à huit, et l'accompagne jusqu'à la porte du jardin — où elle passe la main à une consœur et lui dit au revoir. *C'est le seul personnage du livre dont l'arc soit une durée.*`,
  clef:`✅ **Sa réserve à l'épilogue n'est pas du chagrin : elle sait qu'elle le rejoindra.** *Trouvaille de l'autrice, 17 août 2026.* **On peut rendre visite au jardin — c'est autorisé et ça se fait.** Mais elle ne sait pas combien de temps il lui reste comme berceuse, et une promesse de visite serait donc une promesse qu'elle ne tient pas. *C'est compliqué à répondre, et heureusement Eliott ne le lui demande pas.*

**Conséquence sur ses adieux :** *tu vas être bien là-dedans, mieux qu'avec moi* cesse d'être ce qu'on dit à un mourant. **C'est quelqu'un qui sait que l'endroit est bien, puisqu'elle y sera.** — *Et c'est Andrew qui répond à sa place, une fois qu'elle est partie : « t'inquiète pas, elle viendra te voir, tu la connais ».*`,
  portrait:[`**Écrit par l'autrice, 22 août 2026.** *Elle a tiré ses cheveux blonds en arrière et les a noués bas. Grande et fine, elle a le visage d'une jeune femme au début de la vingtaine. Son tablier a déjà servi ce matin-là, et elle le porte avec cette simplicité des vêtements qu'on enfile pour travailler.*`,
    `🔴 **Le visage d'une jeune femme, et pas un âge.** *La formulation de l'autrice ne dit pas qu'elle a vingt-deux ans : elle dit qu'elle en a le visage.* **C'est exactement le statut d'un âge dans ce monde** — *une apparence, qui ne renseigne sur rien.* ⛔ *Et rien dans la phrase n'invite le lecteur à y voir autre chose.*`,
    `⛔ **Pas une liste d'attributs.** *Première version : « Élancée, des vêtements simples, un tablier par-dessus. »* **Reprise de l'autrice : la description doit être romanesque, pas inventoriée** — *un geste qu'elle a fait le matin vaut mieux qu'un adjectif.*`,
    `⛔ **Rien de strict.** *La coiffure tirée pourrait faire sévère et ne le fait pas — c'est la seule chose que le portrait ait à corriger.*`,
    `**Elle est nommée dès la porte.** *Andrew la connaît : écrire « une jeune femme lui ouvrit » supposerait un narrateur qui la découvre, et le livre n'en a pas.* **Le lecteur reçoit le nom et le visage en même temps.**`],
  gardes:[`Elle ne signale rien et ne vient trouver personne. Toute version qui lui donne ce rôle est périmée.`,
    `Elle n'est pas un relais d'information : elle est un lieu où la nouvelle attend.`,
    `Si une seule de ses répliques a l'air d'appeler Andrew à faire quelque chose, la séquence bascule.`,
    `Ne jamais lui faire dire qu'elle se tait. Le tabou ne se formule pas.`,
    `Sa suspicion se dit une fois, en une demi-phrase, jamais reprise, pas même quand le garçon disparaît.`,
    `Une réplique qui désignerait la berceuse voisine, même en passant, ferait basculer sa fiche.`],
  phrases:[`Un porteur de voiles de cet âge… je n'en avais jamais vu.`,`Il s'est mis dans une colère noire, ça ne lui ressemblait pas.`],
  ouvert:[`Assiste-t-elle aux visites ou laisse-t-elle la pièce ?`,
    `⚠️ **Les âges de Paul et Julie sont à fixer.** *Ils sont arrivés avant Eliott et vivent là depuis plus longtemps que lui ; un berceur accompagne jusqu'à huit ans, où l'on entre au jardin.*`,
    `✅ **Elle est présente à l'épilogue, et c'est elle qui dit l'adieu de huit ans.** Le second, celui de zéro, appartiendra à quelqu'un d'autre.`,
    `La revoit-on entre l'enquête et l'épilogue, ou l'ellipse la garde-t-elle entière ?`,
    `⚠️ **Est-ce que le lecteur peut comprendre qu'elle ira au jardin ?** *Il a tout ce qu'il faut — elle a visiblement rajeuni en six ans, et il connaît la règle.* **Rien ne le lui dit, et rien ne l'en empêche.** À laisser tel quel, probablement : c'est exactement la sorte de chose que ce livre confie au lecteur.`,
    `Que savaient exactement l'une de l'autre les deux berceuses voisines ?`],
  src:`03-personnages/june.md` },

{ id:`paul-julie`, nom:`Paul et Julie`, voie:`andrew`, role:`Les deux autres arrivants de chez June.`,
  age:`🔴 **Paul a huit ans, Julie en a dix — décision de l'autrice, 22 août 2026.** *Paul rejoint le jardin dans quelques semaines.* **Julie est arrivée dans ce monde vers soixante ou soixante-dix ans** — *le livre ne le dit pas et s'en moque.* ⛔ **Elle n'est pas chez June depuis cinquante ans pour autant :** *elle a eu son école, ses tuteurs, un métier, et elle est passée chez une berceuse à quatorze ans comme tout le monde.* **Quatre ans chez June, à peu près.**`,
  resume:`🔴 **Décision de l'autrice, 22 août 2026.** *June n'a pas un arrivant à charge, elle en a trois, et Eliott est le dernier arrivé.* **Ils ne servent pas l'intrigue : ils servent June.** *Elle n'est pas quelqu'un qui peine avec un garçon — elle est quelqu'un qui s'en occupe de trois et qui n'arrive pas à créer le lien avec celui-là.*`,
  traits:[`On les croise, on ne les visite pas. **Une silhouette dans une rue, une porte qui claque, une voix depuis une autre pièce.**`,
    `**Ils ont été très accueillants avec lui, et il est resté distant.** *Décision de l'autrice, 22 août 2026 : aucune animosité, aucun conflit, rien à jouer de ce côté-là.* ⛔ **La distance vient de lui seul** — *il ne trouve sa place nulle part, et cette maison n'y est pour rien.*`,
    `**Julie : cheveux bruns, légèrement ondulés, retenus d'un côté par une pince.** *Décision de l'autrice, 22 août 2026.*`,
    `🔴 **Julie a été couturière vingt-cinq ans, pour un grand magasin de vêtements en ville.** *Le chiffre est passé de onze à vingt-cinq le 23 août 2026 : l'autrice veut que ça choque.* *Décision de l'autrice, 22 août 2026.* **Et sa bienveillance se montre par un ouvrage, pas par une réplique :** *elle s'est proposée pour reprendre toutes les affaires d'Eliott, et c'est June qui le dit, pas elle.* ⛔ *Elle hausse une épaule et rend son sourire ; elle ne se défend jamais d'être gentille.*`,
    `**Paul part au jardin dans quelques semaines**, et personne n'en fait un événement. ⛔ *Et on ne décrit surtout pas ce qu'est une entrée au jardin : l'épilogue est là pour ça.*`,
    `⛔ **Aucun mot de parenté entre eux.** *Ils vivent au même endroit, c'est tout ce qu'on en sait — ni fratrie, ni famille, ni rien qui y ressemble.*`],
  clef:`⚠️ **Son âge doit être sur la page avant ses vingt-cinq ans de couture.** *Repérage de l'autrice, 23 août 2026 : sans lui, le paradoxe passe inaperçu.* **« Elle avait dix ans, comme Eliott »**, dit à sa première apparition. *Chiffre nu contre chiffre nu : trois répliques plus loin, « vingt-cinq ans de métier ».*

❓ **Le mot <em>apparent</em> a été essayé et retiré le 23 août 2026.** *L'autrice a raison sur le fond — il y a bien deux données, l'âge et l'ancienneté, et son dossier les distingue.* **Mais dans le texte le mot prévient le lecteur** : *il annonce l'écart avant que Julie ne parle de ses onze ans, et le lecteur vérifie au lieu de buter.* ⚠️ *À reprendre à la relecture si le passage paraît trop sec.*

🔴 **Julie est l'inversion des âges à hauteur de gamin, et sans un mot d'explication.** *Deux corps de dix ans dans la même maison : l'un est né il y a un mois, l'autre a une vie entière derrière elle — l'école, vingt-cinq ans de couture, des dizaines d'années.* **Et ça passe par ses mains, pas par une explication :** *elle plie un ourlet à l'ongle et le pique sans épingle, et Andrew la regarde faire avant qu'elle ne dise quoi que ce soit.* **Eliott a du mal à le comprendre** — *et c'est tout ce que le livre en dit.*

⛔ **Et c'est lui, le cas rare, pas elle.** *Julie a rejoint la tranche haute à quatorze ans comme tout le monde ; Eliott y est arrivé directement, sans rien derrière lui.*

**C'est Julie qu'Eliott siffle dans la rue, à la tournée.** *— Tu vas où ? — June m'a demandé de récupérer du lait !* **Deux répliques, et on repart.** *C'est par elles que la maisonnée entre dans le livre, sans une phrase d'exposition.*`,
  gardes:[`**Ils sont des témoins, et l'enquête doit les voir.** *On n'interroge pas une maison sans interroger ceux qui y vivent* — **ils sont là tous les deux quand Joël et Liam viennent chez June.**`,
    `⛔ **Ultra-secondaires, et c'est une décision, pas un accident.** *Décision de l'autrice, 22 août 2026 : ils ne reviennent plus après cet entretien.* **Deux apparitions dans tout le livre — une silhouette sifflée dans une rue, et deux témoins qui ne savent rien.**`,
    `⛔ **Ils ne savent rien.** *Ils vivaient avec lui, ils ne l'ont pas suivi au travail, et ce qu'ils disent ne fait avancer personne.*`,
    `⛔ **Aucun des deux ne devient un ami d'Eliott ni un confident.** *Il est le dernier arrivé et il ne trouve sa place nulle part — c'est vrai dans cette maison aussi.*`],
  ouvert:[`✅ **C'est Julie qu'il siffle — tranché le 22 août 2026.**`,
    `⚠️ **Ce qu'ils disent devant Joël et Liam, et si le lecteur l'entend.**`],
  src:`décision de l'autrice, 22 août 2026` },

{ id:`henri`, nom:`Henri`, voie:`andrew`, role:`Le responsable du portage. Celui qui a congédié le marginal.`,
  age:`⚠️ **À fixer.** *Rien ne l'exige pour l'instant.*`,
  resume:`🔴 **Il a un nom depuis le 22 août 2026, et c'est tout ce qui a changé.** *Il tient un effectif, il a congédié un homme de vingt-deux ans après plusieurs sommations, et il donne sa version sans y mettre d'affect.* **Il est blasé comme quelqu'un pour qui ce n'est pas la première fois.**`,
  traits:[`**Blasé, pas cynique.** *Des marginaux il y en a partout, il faut vivre avec en limitant les débordements.*`,
    `**Neutre sur les jeunes arrivants** — ni tendresse, ni mépris. *C'est de la main-d'œuvre, et il en a besoin.*`],
  gardes:[`⛔ **Il ne formule jamais la doctrine.** *Il a un effectif à tenir, c'est tout.*`,
    `⛔ **Sa position sur les jeunes arrivants reste neutre.** *S'il prend parti, la scène devient une tribune.*`],
  phrases:[`On les fait travailler pour que le reste du monde le supporte.`],
  ouvert:[`⚠️ **Ce que le portage porte exactement, à qui, et sur quel périmètre.**`],
  src:`décision de l'autrice, 22 août 2026` },

{ id:`isaac`, nom:`Isaac`, voie:`andrew`, role:`Agent de police, ami d'Andrew.`,
  age:`Non fixé. L'inversion vaut pour la police comme pour la ruche : un ancien du métier a l'air jeune.`,
  resume:`Sa fonction est structurelle : c'est lui qui rend naturelle la présence d'un veilleur dans une enquête criminelle. Il fait appel à Andrew régulièrement, pour des affaires qui n'ont rien à voir — le veilleur est témoin de toutes les arrivées et peut consulter le registre. De cette habitude naît l'amitié, et de l'amitié naît tout le reste. Il enquête sur une disparition, point : il est bon dans son travail, il est fatigué comme on l'est, il a d'autres dossiers.`,
  traits:[`Il sollicite Andrew comme une ressource ordinaire, pas comme un ami à qui on fait plaisir.`,
    `Le poste est un endroit qu'Andrew connaît, où il pousse une porte qu'il a déjà poussée cent fois.`,
    `Il ne soupçonne rien, jamais — ni sur Andrew, ni sur le monde.`,
    `Il part par objectivité, pas par résignation. Il a raison, et c'est ce qui rend son départ insupportable.`],
  faille:`—`,
  arc:`Sa relation avec Andrew donne un accès gradué : il est chez lui au poste tant qu'on veut bien de lui, et le jour où on lui dit de lâcher l'affaire, la porte se ferme sur un homme qui la croyait ouverte. Il ne perd pas un droit, il perd une place.`,
  gardes:[`Il ne sert jamais de porte-parole à une théorie. Pas de doute utile, pas de « et si ».`,
    `L'hypothèse « il fabule » ne survit pas à un policier lucide.`,
    `Ne jamais en faire un lâche, ni un tiède, ni un fonctionnaire.`,
    `Ne jamais lui faire dire qu'il a été trompé — il ne l'a pas été. Il a suivi de trop près quelqu'un qui avait tort, et il le sait sans avoir à le formuler.`],
  phrases:[],
  ouvert:[`Son âge d'arrivée et son apparence.`,`Est-ce le même homme que celui qui dit à Andrew de lâcher l'affaire ?`],
  src:`03-personnages/isaac.md` },

{ id:`chrissy`, nom:`Chrissy et Tania`, voie:`joel`, role:`La paire. L'objet unique de la faute, du remords et des excuses d'Andrew.`,
  age:`Mortes à dix-huit ans, arrivées à dix-huit ans. Une quinzaine d'années pendant le livre — presque exactement l'âge des corps qu'il a trouvés, à trois ans près.`,
  resume:`Dans la vie d'avant, deux sœurs jumelles enlevées et tuées par le même homme, et l'enquêteur est arrivé une heure trop tard. Ici, elles sortent de deux capsules voisines le même jour et produisent chacune leur prénom — les seuls qu'elles porteront jamais. Elles sont identiques en tout, et le monde n'a aucun mot pour ce qu'elles sont l'une à l'autre : une paire, travée douze. Elles sont des meurtries, et la grâce qui leur revient n'est pas un chiffre plus bas mais un plateau allongé.`,
  traits:[`Leur ressemblance émerveille la salle, qui dit simplement « elles sont pareilles ».`,
    `Le seul trait qui les sépare est le mot que chacune a prononcé, et il est sorti d'elles, vides, sans témoin.`,
    `À quinze ans elles ont tous les mots : elles répondent, elles comprennent, elles pourraient très bien demander à Andrew ce qu'il veut.`,
    `Quand il prononce un des deux noms, une seule se retourne.`],
  faille:`—`,
  arc:`Elles ne font rien dans l'intrigue. Elles apparaissent tôt, une fois, comme du décor du monde, puis elles reviennent comme une ligne de registre qu'Andrew cherche et trouve — sans savoir qu'il lit aussi la sienne. À la toute fin, il pousse leur porte un après-midi ordinaire, et il n'obtient ni absolution ni incompréhension : il obtient de la politesse.`,
  gardes:[`Leurs prénoms de la vie d'avant ne sont jamais donnés. C'est un blanc et il reste blanc.`,
    `« Jumelles » et « sœurs » sont réservés à la vie d'avant.`,
    `Le lecteur ne doit jamais pouvoir soustraire : la date appartient au document, l'âge appartient au regard, et les deux ne se croisent jamais dans la même scène.`,
    `Leur âge de quinze ans n'est jamais écrit. Andrew ne pose jamais l'opération.`,
    `Leur apparition précoce ne doit jamais donner de quoi formuler l'hypothèse des deux histoires.`],
  phrases:[`Ils mettent trois fois plus longtemps à descendre, en plus.`,`Lui, il est arrivé à douze. Ça fait une éternité qu'il est là. Il en a dix.`],
  ouvert:[`Sont-elles prises en charge ensemble ou séparées ?`,`Où tombe exactement la réplique du ratio, et dans quelle bouche ?`],
  src:`03-personnages/chrissy-et-tania.md` },

{ id:`berceuse`, nom:`La berceuse coupable`, voie:`andrew`, role:`La ravisseuse. L'exact contraire de ce qu'on cherchait.`,
  age:`Non fixé. Des décennies de service, et elle approche de sa relève — un berceur exerce jusqu'à douze ans. Donc l'apparence d'une adolescente.`,
  resume:`Elle a passé sa vie à donner des arrivants au jardin et n'en a jamais gardé un seul : accueillir, nommer, accompagner, les regarder entrer, puis basculer, puis descendre jusqu'en bas, en sachant chaque fois la date et en se taisant chaque fois. Eliott, lui, n'y est pas encore : dix ans, dehors, il travaille, il parle, il se met en colère — c'est quelqu'un, et dans six ans ce sera fini. Alors elle en garde un, une fois.`,
  faille:`Ce n'est pas une rupture, c'est une érosion. Et le déclencheur est le tabou retourné contre elle : on commence à lui confier des tâches plus simples sans lui dire pourquoi, et elle reçoit le silence qu'elle a imposé à des centaines d'autres. Elle prend un arrivant au moment exact où on commence à la retirer du monde.`,
  traits:[`Elle vit à quelques pas de chez June, dans une maison ordinaire d'une rue ordinaire — les berceuses habitent à côté du jardin.`,
    `Elle est la seule personne au monde qui pouvait emmener un jeune arrivant sans que quiconque se retourne. Lui non plus ne s'est pas retourné.`,
    `Elle a peint, meublé et choisi une cave réaménagée, des semaines avant qu'il y ait quelqu'un dedans.`,
    `Rien sur elle ne se remarque. Si elle est aimable ou douce dans une scène, elle l'est comme tout le monde.`,
    `Elle sort menottée de la maison, déjà prête à être embarquée.`,
    `🔴 **Elle porte une chaîne au cou, symbole de sa foi.** *C'est le seul détail physique que le livre lui donne, et c'est un objet — pas un visage.* **Elle berce à son rythme ; et au moment de l'arrestation, elle la triture avant de tendre les mains.**`],
  arc:`Elle emmène Eliott, qui la connaissait, sans ruse ni force ni piège — le passage à l'acte n'a ni scène, ni seuil, ni bascule : il a la forme exacte de ce qu'elle a fait toute sa vie. Elle le garde deux semaines dans une cave aménagée, vivant, puisque le mobile est de garder et jamais de supprimer.`,
  gardes:[`Rien de son motif ne se dit dans le texte. Elle ne l'explique pas, personne ne le formule à sa place, et le livre n'a pas de scène qui rende son geste intelligible.`,
    `Elle ne doit jamais s'écrire comme une démente qu'on range et qu'on oublie.`,
    `Aucun personnage ne rapproche jamais sa présence ancienne et son arrestation. Pas de « elle était là depuis le début ».`,
    `Si elle apparaît au jardin, elle reste anonyme et non détaillée : un geste, une silhouette, une façon de tenir un poids. Jamais un portrait, jamais un visage, jamais une réplique qui reste.`],
  phrases:[],
  cle:`Elle a passé sa vie à donner des arrivants au jardin. Elle n'en a jamais gardé un seul.`,
  ouvert:[`Andrew lui parle-t-il au jardin, ou la croise-t-il seulement ?`,`Le livre lui donne-t-il un nom, et par lequel des trois canaux possibles ?`,`Ce qu'elle comptait faire ensuite. Rien, probablement — et c'est peut-être la réponse.`,`Ce qu'elle dit, ou ne dit pas, au moment de l'arrestation.`],
  src:`03-personnages/la-berceuse.md` },

{ id:`quarante`, nom:`Nicolas`, voie:`andrew`, role:`Le second arrivant de la première page. Le père d'Eliott dans la vie d'avant. Nom d'éclaircie : Nicolas.`,
  age:`Quarante-deux ans, son âge de mort — *l'autrice, 18 août 2026 : pas de chiffre rond.* Verdict ordinaire, ni supplément ni retranchement.`,
  resume:`Une randonnée prévue entre un père et son fils : l'enfant tombe à l'eau, le courant l'emporte, il se jette pour le sauver et se noie à son tour. Personne n'a commis l'irréparable, il n'y a rien d'autre à trouver, personne à qui en vouloir, et aucune enquête possible d'aucun côté. Les deux capsules surgissent donc le même matin, à quelques travées l'une de l'autre — une noyade ne laisse aucun délai de maturation — et la cérémonie se monte dans la journée.`,
  traits:[`Un corps debout à côté d'un autre, à la première page, qui sort du livre à la fin du chapitre.`,
    `Il est ce qu'Eliott dévisage deux secondes sans savoir pourquoi.`,
    `Puis ils sont affectés ailleurs et ne se revoient jamais.`],
  faille:`—`, arc:`Il n'intervient pas dans l'histoire.`,
  gardes:[`Il n'a ni fiche, ni scène, ni réplique, et il ne faut jamais lui en donner davantage. Tout ce qu'on lui ajouterait ferait de la scène une annonce.`,
    `Aucune phrase de narrateur ne rapproche les deux arrivées. Andrew ne retourne jamais au registre pour chercher qui d'autre est arrivé ce jour-là.`,
    `Les mots de parenté ne valent que pour la vie d'avant.`],
  phrases:[],
  ouvert:[`✅ **Son nom d'éclaircie est Nicolas** — *validé par l'autrice le 17 août 2026.* **Il apparaît deux fois, première page et scène 8**, et rien ne doit inviter à le rapprocher de celui d'Eliott.`,
    `Combien de lignes doit durer le dévisagement.`],
  src:`03-personnages/eliott.md` },

{ id:`marginal`, nom:`L'homme de vingt-deux ans`, voie:`andrew`, role:`La fausse piste. Le grief, dans une bouche.`,
  age:`Vingt-deux ans.`,
  resume:`Il appartient au milieu jaloux que tout le livre montre. Il a voulu bloquer une entrée au jardin, et il a fait des jours « au silence » pour ça. C'est vers ce milieu que l'enquête cherche son coupable, et le lecteur avec elle. Il n'y en a pas.`,
  traits:[`Il est allé jusqu'au geste, là où le reste du milieu s'en tient aux paroles.`,
    `Il a un alibi parce qu'il est bruyant : il crie, il est connu pour crier, tout le monde peut dire où il était.`,
    `Il envoie promener les enquêteurs sans rien démontrer, parce qu'il n'a pas à se justifier.`],
  faille:`—`,
  arc:`Le climat dont il fait partie garde toute sa place et paie le lecteur en monde, mais il ne mène plus à personne.`,
  gardes:[`Le grief reste réel, jamais caricatural, et on ne demande jamais d'y adhérer.`,`La piste ne doit mener à rien.`],
  phrases:[],
  ouvert:[`Son prénom. Un nom d'éclaircie. Il traverse huit scènes sans être nommé.`],
  src:`02-univers/la-jalousie.md` },

{ id:`liam`, nom:`Liam`, voie:`joel`, role:`Le collègue de Joël — et le visage que le lecteur prêtera à Isaac.`,
  age:`—`,
  resume:`Le partenaire de l'enquêteur. **Il porte bien plus qu'un cri désormais** : c'est lui qu'on rencontre au commissariat — et le lecteur, qui vient d'entendre parler d'Isaac, croit rencontrer Isaac. C'est lui aussi qui renseigne au téléphone. Et à la fin, quand Joël s'élance derrière le fuyard, c'est lui qui crie.`,
  traits:[`Il voit ce que Joël va faire, et il essaie de l'arrêter.`,`Il ne sait rien de ce que son cri produira, ni de l'écho qu'il fait à la faute de son collègue.`],
  faille:`—`,
  arc:`Il traverse la voie de Joël d'un bout à l'autre — le commissariat, le téléphone, la planque, le cri — sans jamais être nommé.`,
  gardes:[`Le mot « Liam » n'est écrit dans aucune page du roman. Dans le texte il reste son collègue, son partenaire, l'un d'eux.`,
    `Il ne relève jamais l'écho entre son cri et la faute de Joël, et il n'a aucune raison de le faire.`],
  phrases:[`Joël, non, attends !`],
  ouvert:[],
  portrait:[`**Donné par l'autrice le 23 août 2026.** **Grand, la silhouette large et pleine.** *Les épaules donnent de l'ampleur à sa carrure ; le torse et les bras sont solides sans être athlétiques.*`,
    `**Le teint sombre, le visage large, les traits réguliers et expressifs.** *Des sourcils épais et très noirs encadrent des yeux presque noirs, profonds et attentifs. Un nez large, accordé aux proportions du visage. Des lèvres pleines, qui adoucissent l'ensemble malgré la force des traits.* **Une barbe noire, dense et soigneusement entretenue**, qui souligne la mâchoire et remonte un peu sur les joues.`,
    `🔴 **Liam est d'origine indienne — décision de l'autrice, 24 août 2026.** *C'est ce qui le sépare d'Andrew d'un seul coup, au lieu des deux adjectifs que je cherchais.*

⛔ **Mais le mot ne s'écrit jamais.** *L'Inde est un lieu de notre monde : l'interdit n° 6 l'exclut du texte.* ⛔ **Et le mot <em>peau</em> est proscrit partout** — *décision du 19 août.* ✅ **On écrit donc le teint, les traits, le noir des cheveux, et rien d'autre.**

✅ **Et l'impossibilité de le nommer est un cadeau :** *dans un monde où tout le monde sort d'une capsule, une apparence ne renvoie à aucune origine — le mot lui-même n'aurait pas de sens là-bas.* **Le lecteur voit un homme, pas une provenance.**`,
    `**Cheveux noirs, épais, légèrement ondulés** — plus courts sur les côtés, retombant avec naturel sur le dessus. *Quelques mèches se détachent et reviennent vers le front.*`,
    `**Les mains grandes, les poignets épais, la posture droite.** *Il dégage une présence tranquille, qui tient plus à son regard et à l'assurance de ses gestes qu'à sa carrure.*`,
    `🔴 **Ce portrait est le seul que le lecteur lira d'un policier, et c'est tout l'enjeu.** *Isaac n'est jamais décrit, nulle part.* **Quand le lecteur imaginera Isaac, il lui donnera ce visage-là** — et il ne saura qu'à la dernière page qu'il regardait quelqu'un d'autre.`,
    `✅ **Le risque de confusion avec Andrew est levé.** *Le portrait initial disait presque les mêmes choses que le sien — sourcils épais, yeux bruns attentifs, nez droit, barbe, mèches sur le front, épaules larges.* **Le teint et le noir des cheveux les séparent maintenant sans qu'on ait à y revenir**, et le lecteur voit deux hommes dans la pièce.`],
  src:`03-personnages/andrew.md` },

{ id:`pediatre`, nom:`Le pédiatre du jardin`, voie:`andrew`, role:`Celui qui a suivi l'autre arrivant. Il ne refuse rien.`,
  age:`Non fixé. Il exerce au jardin, donc il est bien au-dessus de huit ans.`,
  resume:`Il a suivi l'arrivant dont les traces s'arrêtent. **Il est un peu sur la réserve quand ils arrivent — puis il comprend qu'il a affaire à un policier, et il coopère normalement.** Il est très occupé : il leur propose de le suivre pendant qu'il répond, et c'est comme ça qu'ils traversent le jardin.`,
  traits:[`Il marche vite et parle en marchant. **Il ne s'arrête pas pour répondre**, sauf une fois.`,
    `Il ne s'excuse pas et ne se justifie pas : il applique une règle, puis il en applique une autre.`,
    `Il connaît la date de chaque enfant dont il a la charge, et c'est la seule chose qu'il ne dira jamais, même à un policier.`,
    `**Devant la salle, il laisse passer.** Il sait que c'est rare de voir ça quand on est extérieur au jardin, et il ne dit rien.`],
  faille:`—`,
  arc:`Il apparaît une fois, le temps d'un couloir. Il ne revient pas.`,
  gardes:[`**Il n'explique jamais le fonctionnement du jardin.** Il répond à des questions qu'on lui pose, entre deux portes, et il s'arrête là.`,
    `Ce qu'il dit ne touche jamais le registre : l'erreur est dans les dossiers d'après.`,
    `**Ce n'est pas lui qui refuse.** Le refus est administratif, en amont — un secrétariat qui donne son nom et ce qu'il fait maintenant, et rien de plus.`,
    `Devant la salle, il ne commente pas. *Ni avant, ni pendant, ni après.*`],
  phrases:[],
  ouvert:[`Son nom, s'il en a un dans le texte.`,`Combien de questions il répond avant l'arrêt devant la salle.`],
  src:`décision du 16 août 2026` },

{ id:`berceuse-salle`, nom:`La berceuse de la salle`, voie:`andrew`, role:`Celle qu'Andrew regarde bercer un mourant, scène 14 · c.`,
  age:`Non fixé — et elle ne doit surtout pas être située. *Un âge apparent la rendrait comparable, donc identifiable.*`,
  resume:`En tête à tête avec un tout-petit sur le point de disparaître. **Une scène presque de mère et d'enfant, dans une grâce et un amour profonds** — et le mot est impossible à écrire, ce qui oblige à le faire tenir entièrement dans les gestes. **Elle berce au rythme de la chaîne qu'elle porte au cou, symbole de sa foi.**`,
  traits:[`Elle porte, elle berce, elle tient au chaud. Des gestes de métier, faits des centaines de fois.`,
    `Elle ne pleure pas et ne prend pas un ton. **Le chagrin est en elle, jamais dans la phrase.**`,
    `**Une chaîne au cou**, et le bercement en suit le rythme.`],
  faille:`—`,
  arc:`Elle apparaît une fois, quelques minutes, à travers une porte. Personne ne lui parle.`,
  gardes:[`**Aucun visage, aucun nom, aucune réplique.** Un geste, une silhouette, un objet — jamais un portrait.`,
    `Personne ne la présente et personne ne la commente. Ils regardent, puis ils repartent.`,
    `**Rien ne la désigne comme importante.** Si le texte s'attarde sur elle plutôt que sur ce qu'elle fait, tout est perdu.`],
  phrases:[],
  cle:`**Et si c'était elle.**`,
  ouvert:[`✅ **Est-ce la ravisseuse ? Le livre ne le dira jamais.** *Décision de l'autrice, 16 août 2026 : le doute reste.* **Le lecteur observateur se dira peut-être que c'est la même**, il l'aura vue porter un mourant avec une tendresse parfaite, il aura trouvé ça beau — *et il n'obtiendra aucune confirmation.* **La chaîne est le seul fil entre les deux scènes, et personne dans le livre ne le relève.**`,
    `*Ça vaut aussi pour l'écriture : on écrit la scène sans savoir, donc on n'y met rien qui désigne.*`],
  src:`02-univers/le-jardin.md §6 — décision du 16 août 2026` },

{ id:`la-mere`, nom:`Leur mère`, voie:`joel`, role:`Le pendant de June. La vie d'avant.`,
  age:`—`,
  resume:`C'est chez elle que Joël retourne pour ce que le procès-verbal n'a pas retenu : l'état d'esprit, les habitudes, ce qui n'allait pas. **Elle raconte ce qu'elle a vu, et elle a peur.**`,
  traits:[`Elle a déjà tout dit une fois, à quelqu'un qui notait des trajets.`,`Elle répond, elle ne demande rien.`],
  faille:`—`,
  arc:`Elle n'apparaît pas. Le livre ne dit rien d'elle, et c'est le lecteur qui, à la relecture, saura qu'elle existait.`,
  gardes:[`**Elle n'a pas de scène, et n'en aura pas.** Cette fiche est un repère d'écriture : savoir ce qu'il y a de ce côté-là pendant qu'on écrit June.`,
    `Le parallèle avec June n'est jamais souligné, ni par un personnage ni par le narrateur — et pour cause, il ne se voit nulle part.`],
  phrases:[],
  ouvert:[`Le livre la montre-t-il une fois ou deux ?`],
  src:`décision du 16 août 2026` },

{ id:`mere`, nom:`L'arrivante de trente-cinq ans`, voie:`andrew`, role:`Hors casting — en réserve.`,
  age:`Trente-cinq ans. Vingt-sept marches avant le jardin, à une vitesse qui n'est fixée nulle part.`,
  resume:`Elle et l'enfant qu'elle attendait étaient réunis au moment où leurs deux vies se sont arrêtées ; le livre ne dit pas comment. Deux capsules se forment ensemble et s'ouvrent le même jour. Elle produit son nom elle-même pendant qu'à côté, une inconnue qu'on a fait venir choisit le mot d'un petit chiffre. Elle insiste ensuite pour devenir berceuse, avec un sérieux que personne ne s'explique, elle-même comprise : elle ne se rappelle rien, elle y retourne.`,
  traits:[`Sa vocation est un reliquat pur.`,`Elle ne sait pas, et ne peut pas savoir, ce que cet enfant est pour elle — ce lien n'a pas de nom ici, et pas d'existence non plus.`,`Elle deviendra à son tour celle qu'on appelle pour nommer un arrivant qui n'est rien pour elle.`],
  faille:`—`,
  arc:`Deux courbes qui vont l'une vers l'autre sans jamais se superposer.`,
  gardes:[`Elle n'est pas porteuse de voiles. Jamais de souvenir, jamais de vertige, jamais de reconnaissance.`,
    `Aucun personnage ne commente sa vocation.`,
    `Elle devient berceuse ; elle ne devient pas sa berceuse.`,
    `Ne jamais dater, ne jamais expliquer, ne jamais employer de vocabulaire clinique.`],
  phrases:[],
  ouvert:[`Tout est suspendu tant que l'autrice ne réintègre pas ce couple. Le service qu'elle rendait — apprendre au lecteur qu'une journée à deux arrivées signifie une seule mort — a été repris par la scène d'ouverture.`],
  src:`03-personnages/la-mere-et-l-enfant.md` }
];

/* ==========================================================================
   LE DISPOSITIF ET LES FAUX RACCORDS
   ========================================================================== */

const DISPOSITIF = [
["Deux récits, une voix","Deux histoires racontées simultanément, entremêlées chapitre après chapitre, et délibérément données à lire comme une seule. Deux temporalités qui ne communiquent pas, deux récits sans aucun point de contact, et une seule voix pour les porter."],
["Deux enlèvements","C'est ce qui rend la confusion possible autant qu'honnête : le lecteur ne se trompe pas parce qu'on lui cache quelque chose, il se trompe parce que les deux récits racontent la même chose. La ressemblance n'est pas fabriquée, elle est réelle."],
["Il n'y a pas de fragments","**Décision du 16 août 2026 : le mot n'a plus cours.** Les chapitres de la vie d'avant ne sont ni des éclats, ni des flashs, ni des inserts — ce sont des chapitres entiers, de même longueur et de même facture que les autres. *Un fragment se repère ; un chapitre, non.* Et aucun d'eux n'établit l'affaire : elle est déjà là quand on entre dedans, comme dans la vie."],
["Les reliquats ne sont jamais nommés","Le mot, la notion, l'explication : rien. Aucun personnage ne dit qu'il se souvient, aucun narrateur ne signale un basculement, aucune typographie ne trie les chapitres."],
["Temps 1 — une seule enquête","De la première page jusqu'au seuil du lieu de séquestration. La contrainte n'est pas « il ne doit pas comprendre » mais : il ne doit pas même se poser la question. Un lecteur qui formule l'hypothèse et la met de côté a déjà tout perdu — il ne lira plus les chapitres, il les triera."],
["Temps 2 — le trouble","La découverte des corps. Le lecteur peut se dire « la paire du début, qu'est-ce qu'elles font là ? », et c'est admis, c'est même souhaitable. Ce n'est pas encore la bascule : c'est une pièce de trop dans les mains, sans case où la ranger. Il n'a pas d'hypothèse, il a un inconfort."],
["Temps 3 — le chapitre qui recommence","Même lieu, même arrivée, même lourdeur, autre issue. C'est là, et seulement là, que le lecteur comprend qu'il y a deux histoires. Il ne le reçoit ni d'une phrase ni d'un personnage : il le reçoit de la forme du livre, qui se dédouble sous ses yeux."],
["Temps 4 — le cri","« Joël, non, attends ! » Le temps 3 avait appris qu'il y avait deux histoires ; le temps 4 apprend qui est le second homme et referme le livre d'un coup. Le nom ne révèle pas le dispositif, il révèle l'identité."],
["Temps 5 — le registre","La ligne d'archive ne révèle rien de neuf : elle confirme, et elle confirme par un document. C'est le bon ordre — le lecteur devine, puis on lui prouve."],
["Le nom arrive attaché à un refus d'obéir","La seule fois du roman où l'on entend son nom est la seule fois où quelqu'un essaie de l'arrêter et où il n'écoute pas. Son partenaire crie « attends » — le mot exact auquel il a cédé des semaines plus tôt, et qui est toute sa faute. Son identité et sa faute sont données dans le même souffle, et en miroir."],
["Ce n'est pas une entourloupe (1)","Andrew enquête comme l'enquêteur parce qu'il est l'enquêteur : le reliquat n'est pas un souvenir, c'est une vocation. La ressemblance des deux récits n'est pas une astuce d'autrice, c'est une règle énoncée par le livre avant que le lecteur ait à s'en servir. Il a été trompé par une cohérence, pas par une omission."],
["Ce n'est pas une entourloupe (2)","Les deux mondes ont des postes de police, des procédures, des voitures, des dossiers. Une scène d'enquête ne trahit jamais lequel des deux on lit — non parce qu'on gomme les indices, mais parce qu'il n'y en a pas à gommer."],
["Le lecteur est dans le monde d'ici, tout du long","**Doctrine arrêtée le 16 août 2026.** Pour lui, l'enquête est celle de la disparition d'Eliott, du premier chapitre au dernier. De temps en temps, un chapitre traite l'affaire des filles du point de vue de Joël — et il ne le soupçonne jamais. Rien ne le signale : ni titre, ni typographie, ni changement de voix. **Ce sont les faux raccords, semés trois ou quatre fois dans tout le volume, qui le lui apprendront à la seconde lecture.**"],
["La couture","Le lecteur recoud deux morceaux de deux vies en un seul souvenir, et la couture ne se voit pas parce que c'est lui qui l'a faite. *Le procédé a changé d'échelle : il ne porte plus une phrase, il porte des chapitres entiers.*"],
["Le suspect est une couture","**Il n'existe pas.** Les scènes 6, 7 et 9 construisent un homme du monde d'ici — vingt-deux ans, des propos haineux, des jours au silence. Les scènes 12 et 13 montrent un homme du monde d'avant, qui a tenu des propos déplacés à deux filles. Le lecteur n'en voit qu'un. **Deux hommes qui ne se sont jamais rencontrés et qui ne vivent pas dans le même monde, et l'alibi de la scène 13 les tue tous les deux d'un coup.**"],
["L'équivoque","Le procédé qui rend la méprise possible, et il ne se confond pas avec le faux raccord. **Le faux raccord différencie ; l'équivoque, elle, autorise deux lectures d'un même mot.** *Des propos déplacés* : le lecteur y entend l'euphémisme du grief anti-jeunes, et ce sont des propos sexistes. *Vous en seriez venus aux mains* : une bagarre au travail, dans les deux mondes. **Aucune des deux lectures n'est fausse, et c'est pour ça que rien ne se démonte à la relecture.**"],
["La couture obéit à d'autres règles","Elle ne consomme aucune paire du dosage, puisqu'elle ne produit aucun soupçon au premier passage. Et la règle d'espacement s'inverse : une paire doit être très écartée pour qu'on oublie ; ici il faut qu'on se souvienne. Assez près pour que la couture prenne, assez loin pour qu'elle ne se regarde pas."],
["L'escalier et la porte","Le lecteur descend deux fois le même escalier et ouvre deux fois la même porte : là-bas un mouroir et deux corps, ici une cave repeinte, meublée, et quelqu'un de vivant. C'est le seul endroit du livre où le procédé produit son effet par la différence et non par la ressemblance."],
["Les deux cérémonies","Deux descriptions du même rite, toutes deux du point de vue d'Andrew : celle où il accueille (analytique) et celle où il est accueilli (l'accueilli qui ne comprend rien). Le même rite vu depuis les deux bouts — et le lecteur ne réalise pas tout de suite que le second point de vue est celui du même homme."],
["La même phrase, fausse deux fois","Dite à Joël au milieu de l'affaire, alors que les filles sont vivantes : il obéit, il perd des semaines, elles meurent moins d'une heure avant qu'il arrive. Dite à Andrew, alors qu'Eliott est vivant : il refuse, et Eliott est vivant. Personne n'a menti — les deux policiers avaient raison sur le calcul et tort sur le cas."],
["Rien ne se commente","Aucun personnage ne relève l'écho, aucun narrateur ne souligne la ressemblance, et le mot « attends » n'est ni répété, ni souligné, ni mis en italique. Si l'écho se voit, c'est l'autrice qu'on entend."],
["La soupape n'est pas une fuite","Le lecteur doit pouvoir se dire « bizarre » ; il ne doit jamais pouvoir se dire « ce sont deux histoires ». Le trouble doit rester sans destinataire — dès qu'il peut le poser à un personnage ou à une page précise, il devient une piste."],
["Ce que ça coûte aux victimes","La règle « aucun nom dans la vie d'avant » a été écrite pour protéger l'enquêteur ; elle atteint aussi les deux filles, qui traversent tout le livre comme « les deux filles », « elles ». Ce qui protège le protagoniste prive les victimes de leur nom — ce n'est pas un effet secondaire, c'est le même geste."]
];

const RACCORDS = [
["La main","« Il leva son poignet droit pour regarder l'heure » — droitier, la montre au poignet de la main non directrice.","« Quand son collègue lui demanda l'heure, il lui tendit machinalement son bras gauche » — gaucher ; le bras ne se lève pas vers soi, il se tend vers un autre.","Deux membres très espacés, dans des scènes où regarder l'heure est le geste le plus banal. On n'écrit jamais « il était gaucher ».","retenu"],
["La cicatrice","Une cicatrice au visage, qu'il voit le matin en se rasant. La lame qui passe dessous, la peau qu'on tend, le geste qui ralentit d'un demi-temps au même endroit depuis des années.","Aucune marque. Un collègue peut lui lancer sans y penser : « Tu as de la chance, toi, tu es immaculé depuis toujours. »","Côté vie d'avant, dans une scène de rasage où l'on ne voit que la marque et jamais un visage. Ici, une réplique qui parle du monde et non de lui.","retenu"],
["La langue — les mots de parenté","Mère, père, fils, frère, sœur, famille, jumeau : partout. On peut écrire « comme si les jumelles avaient pu être ses propres filles ».","Ces mots n'existent pas. La phrase n'a aucune forme possible de ce côté-ci : il faut inventer des tournures en permanence — celui dont elle a la charge, l'arrivant qu'elle accompagne, les deux qui se ressemblent.","Partout, tout le temps, dans chaque page et chaque dialogue de ce monde-ci. Il ne se plante pas et ne se dose pas : il joue entièrement par l'absence.","structurel"],
["La langue — les noms de famille","L'affaire porte un nom de famille : « l'affaire Sorel ». Un seul mot qui couvre les deux sœurs sans en désigner aucune.","Personne n'a de nom de famille, et la règle n'est jamais énoncée dans le roman.","Un marqueur présent d'un seul côté est un tri ; un marqueur absent d'un seul côté n'en est pas un.","structurel"],
["La langue — « enfant » et « vieillard »","Ces mots existent et s'emploient normalement. La description de la planque a tous les mots et peut dire ce qu'elle voit.","Remplacés par l'âge. « Une chambre d'enfant » ne peut pas s'écrire : il faut décrire les couleurs, la hauteur d'une table, un lit court.","Point le plus chargé : les deux caves, où une seule des deux descriptions a le droit de dire ce qu'elle voit.","structurel"],
["Le mot qu'il ne peut pas classer","On lui dit « l'affaire Sorel », et c'est ainsi qu'on nomme une affaire.","Il entend un mot dont il ne peut pas identifier la catégorie : pas de case où le ranger, pas d'usage à lui supposer. Il ne peut même pas savoir que c'est un nom, donc il ne le retient pas, ne le note pas, ne le cherche pas.","Au comptoir du poste de police, si l'autrice décide qu'il lâche le mot. Les deux versions tiennent et aucune n'est retenue.","ouvert"],
["Le numéro","Rien. Il n'existe pas dans la vie d'avant et ne se compare à rien.","Chaque arrivant reçoit un numéro. Andrew l'écrit sur des formulaires depuis dix ans sans le regarder.","À faire passer plusieurs fois sous les yeux du lecteur avant le temps 5, en n'ayant jamais rien voulu dire. Trop peu, la reconnaissance ne repose sur rien ; trop appuyé, on annonce la scène.","retenu"],
["La vue","L'un tient un papier à bout de bras pour le lire.","L'autre non.","Dans deux scènes de lecture de document, dont le livre ne manque pas.","piste"],
["La taille","Face au même type d'interlocuteur, l'un lève les yeux.","L'autre les baisse.","L'indice n'est jamais dans une mesure, il est dans une direction du regard.","piste"],
["Une dent ébréchée","Une dent qu'on cherche de la langue sans y penser, manie involontaire jamais nommée.","Absente.","À semer comme un tic corporel, jamais commenté par personne.","piste"],
["Une articulation","Un genou au froid, une épaule le matin — une vieille blessure qui rappelle.","Rien ne fait mal.","Ne jamais laisser un personnage dire qu'il n'a jamais eu mal : ce serait un signalement, pas une phrase sur le monde.","piste"],
["Le contre-exemple — le prénom","Joël.","Andrew.","Ce n'est pas un faux raccord et il n'entre pas dans le dispositif : un prénom n'est jamais anodin isolément, il n'est pas un fait de corps, et il ne peut pas s'espacer. Ce qui identifie ne se sème pas, ce qui différencie se sème.","écarté"]
];

/* règles d'usage des faux raccords */
const RACCORDS_REGLES = [
`Jamais commenté par un personnage — sauf une remarque portant sur le monde et non sur lui.`,
`Parfaitement plausible isolément. Seule la paire se contredit.`,
`Physique et involontaire. Jamais une opinion, un savoir ou un goût.`,
`Très espacé.`,
`Invisible à la première lecture, évident à la seconde.`,
`Trois ou quatre paires dans tout le roman — l'arbitrage penche vers trois — dont au moins une tardive, dans le dernier tiers mais avant le cri.`,
`Et surtout : aucune paire nette avant la découverte du lieu de séquestration.`
];
