const TEXTES = [{
  id: `prologue`,
  rang: `Prologue`,
  titre: `La cérémonie`,
  scene: `ouv`,
  sous: `La cérémonie d'Eliott et de Nicolas · point de vue d'Andrew · écrit avec l'autrice les 17 et 18 août 2026`,
  p: [

[`p`,`Deux capsules étaient venues pendant la nuit, et personne ne savait qui allait en sortir.`],
[`p`,`On lui avait donné la salle 4 pour les deux.`],
[`p`,`C'était trop grand, et il n'avait rien dit. On ne discute pas une salle, et surtout pas celle qui était libre.`],
[`p`,`Le veilleur poussa la porte, les bras chargés, et le soleil lui arriva dessus d'un coup. Il entrait par les ouvertures ménagées entre les nervures du plafond et posait sur les dalles de longues bandes obliques. Contre le mur du fond, un coulant passait. Épais comme un bras, entré par une percée du mur, enroulé autour de deux colonnes, ressorti plus loin sans qu'on sache où il allait.`],
[`p`,`Personne ne l'avait planté là. On avait bâti autour, et on avait sculpté tout le reste.`],
[`p`,`Les colonnes étaient couvertes du pied au chapiteau. Des feuilles, des tiges, des grappes lourdes, et dans les feuilles des corps, des mains, des visages tournés vers le milieu de la pièce. Sur la troisième en partant du seuil, la sculpture montait jusqu'à mi-hauteur et s'arrêtait net. Le coulant prenait le relais et continuait jusqu'en haut.`],
[`p`,`On ne savait pas laquelle des deux avait copié l'autre.`],
[`p`,`Il posa ses affaires sur la desserte. Vingt-deux chaises empilées contre le mur, en quatre piles inégales. Il n'avait pas décidé de les compter.`],
[`p`,`Deux capsules, deux postes.`],
[`p`,`Il déplia la lampe sur pied à hauteur d'épaule, orientée vers le sol, et fit rouler un premier miroir depuis le mur jusqu'à l'emplacement du poste. Il stoppa sa course en activant le frein. Il l'essuya avec le linge accroché à la barre, en commençant par le haut, recula d'un pas, se vit dedans, et le tourna vers le mur. Une bassine à droite, vide, avec les flacons dedans.`],
[`p`,`Quand il eut terminé de mettre le premier poste en place, il s'affaira au deuxième, réitérant deux mètres plus loin : lampe, miroir, bassine.`],
[`p`,`Restait la table. Elle trônait au milieu de la pièce, dans la bande de soleil qui tombait là à cette heure-là. Il prit sur la desserte une nappe blanche et toute lisse, ainsi que son chemin de table, une grande bande rectangulaire orangée. Il les ajusta sur le plateau immaculé avant d'y déposer un pichet d'eau au milieu. Un aller-retour à la desserte : deux verres, deux timbales, deux biberons. Il en disposa trois devant chaque place.`],
[`p`,`On ne pariait pas. Alors on posait les trois, on prenait celui qu'il fallait le moment venu et on remettait les deux autres sur la desserte sans y penser. La pile de serviettes suivait le même principe : quatre tailles, et il en descendit une de chaque.`],
[`p`,`Il compta les éléments sur la table. Sept. On était bon.`],
[`p`,`Il récupéra deux chaises du tas.`],
[`p`,`Les visiteurs arrivèrent avant les capsules, comme toujours, par petits groupes, et ils s'installèrent le long des murs en parlant à voix basse. Ils s'appliquaient à parler bas. C'était une chose qu'on faisait ici sans que personne l'ait jamais demandé. On avait prévenu tard, alors ils n'étaient pas nombreux. Ils étaient douze, et ils tenaient tous sur un seul côté.`],
[`p`,`Deux marches basses couraient le long de ce mur-là, pour ceux de derrière. Trois s'assirent dessus, les autres restèrent debout. Ils n'avaient pas d'âge commun : une femme qui en paraissait quatre-vingts, deux hommes autour de la cinquantaine, un autre d'une vingtaine d'années qui les connaissait tous et les appelait par leur prénom.`],
[`p`,`Nora entra la dernière, en nouant ses manches.`],
[`tiret`,`— Bonjour Andrew. On est deux ?`],
[`tiret`,`— On est deux.`],
[`tiret`,`— Alors c'est un bon jour.`],

[`pause`,`· · ·`],

[`p`,`Deux nouvelles personnes, des préparateurs, entrèrent à leur tour et firent rouler deux chariots jusqu'à leur poste respectif ; un murmure parcourut le petit groupe.`],
[`p`,`Ils étaient de la serre. C'étaient eux qui vivaient au milieu de la coulée, qui la suivaient d'un bout à l'autre, qui savaient déterminer à la main quand une capsule était prête et qui, après validation interne, la décrochaient.`],
[`p`,`Les deux éclaircies du jour étaient couchées côte à côte, comme on les avait cueillies. Une capsule, ça ne pousse pas debout : ça pousse à plat sur le coulant, en rang avec les autres, et il faut la détacher de ce qui la porte. Celles-ci étaient venues dans la nuit, toutes les deux, d'un coup, à quelques travées l'une de l'autre, et il avait fallu monter la cérémonie au matin.`],
[`p`,`Elles faisaient la longueur d'un corps et un peu plus. Larges au milieu, effilées aux deux bouts, avec cette dissymétrie qu'ont les choses qui ont poussé : un flanc plus plein que l'autre, une courbe qui reprenait là où on ne l'attendait pas. Des nervures couraient sur toute la longueur, très fines, serrées près des pointes et écartées au ventre, et elles se rejoignaient sans jamais tout à fait se toucher. Rien là-dedans n'avait été dessiné.`],
[`p`,`Elles étaient belles. La paroi avait pris ce jaune très pâle qui vient à la fin, presque comme de la cire, et par endroits on voyait au travers. Une ombre plus dense, une courbe, quelque chose de replié. On ne distinguait rien de plus. Là-dedans, tout se confondait avec le fond, et ceux qui prétendaient reconnaître un genou ou une épaule à travers une paroi mentaient, ou débutaient.`],
[`p`,`Sur le dessus, le rabat était en place, plus sombre et plus mat que le reste. Personne n'y avait taillé quoi que ce soit : à ce stade la paroi est si fine qu'elle finirait par céder toute seule, et on ne fait pas d'entailles à une chose qui va s'ouvrir sans vous.`],
[`p`,`Le reste avait été fait ailleurs, par d'autres mains. Nettoyées, branchées, relevées une dernière fois.`],
[`p`,`Les préparateurs redressèrent les chariots. Les capsules passèrent de l'horizontale à la verticale en trois crans, très lentement, avec un bruit de crémaillère que tout le monde entendit.`],
[`p`,`Un des préparateurs lui tendit les deux fiches de cueillie, puis rejoignit son collègue, déjà droit et immobile, les mains croisées devant lui, sur une des bordures de la salle. Andrew les parcourut en diagonale et les rangea dans son carnet. L'heure de la cueillie, et l'état de chaque capsule avant cérémonie.`],

[`pause`,`· · ·`],

[`p`,`Il prit le rabat à deux mains et le replia d'un quart. Ça ne cassait pas, ça pliait, et ça tenait où on le laissait. Un quart, pas plus : le visage, la gorge, le haut des épaules. Le reste attendrait le second veilleur.`],
[`p`,`La lumière entra dedans.`],
[`p`,`Le corps eut un mouvement — pas un sursaut, un ralentissement de tout, comme quelqu'un qu'on tire d'un sommeil trop profond et qui remonte par paliers. Les paupières bougèrent sans s'ouvrir. Elles s'ouvrirent, se refermèrent aussitôt sur la lumière, se rouvrirent à moitié. Les pupilles mirent longtemps à se faire.`],
[`p`,`On chuchota « douze » le long du mur, et « treize » plus loin.`],
[`p`,`Un voile de gelée le recouvrait entièrement, orange, épais, mat, sans une goutte nulle part. Ça ne coulait pas, cette chose-là. Ça s'enlevait. Andrew posa la main à plat sur l'épaule et fit descendre la paume : le voile vint d'un seul tenant, roulé sur lui-même comme la pelure d'un fruit, et découvrit le bras et la main, qui étaient parfaitement propres et parfaitement secs. Il le déposa dans la bassine. Il recommença sur l'autre épaule.`],
[`p`,`Le corps était placé comme on se place pour dormir quand on n'a mal nulle part.`],
[`p`,`Le veilleur sortit un instrument — étrange pour qui ignore à quoi il sert, banal pour qui sait le manier. Il fit le relevé. Puis, comme un exercice exécuté depuis des années, il trancha pour tous.`],
[`tiret`,`— Capsule éclaircie, arrivant réactif. L'Archiviste lui a compté dix ans.`],
[`tiret`,`— Dix ans, répéta le visiteur d'une vingtaine d'années. C'est si rare !`],
[`p`,`Plus loin sur la marche, quelqu'un souffla par le nez. Personne ne se retourna.`],
[`p`,`Andrew fit pivoter le miroir sur son pied et le régla en biais, à la bonne hauteur, un peu de trois quarts.`],
[`p`,`Le garçon se vit.`],
[`p`,`Il resta là-dessus un long moment. Sa respiration changea de rythme deux fois.`],
[`p`,`Puis il regarda les différents visages qui s'attardaient sur le sien, l'autre capsule à deux mètres de la sienne, et le plafond, qu'il interrogea du regard pour comprendre d'où venait la lumière.`],
[`p`,`Puis le regard du garçon se posa sur lui.`],
[`p`,`C'était le signe ; on ne parlait jamais avant.`],
[`tiret`,`— Bienvenue à toi.`],
[`p`,`Il attendit.`],
[`tiret`,`— Ici, chacun a un mot qui le désigne. Un seul, et c'est le sien, et il ne changera pas. Comment veux-tu qu'on t'appelle ?`],
[`p`,`Le jeune arrivant répondit sans réfléchir une seconde, comme on répond à une question dont on connaît la réponse depuis toujours.`],
[`tiret`,`— Eliott.`],
[`p`,`Andrew écrivit le mot sur son carnet, et à la suite le numéro qu'il porterait toute sa vie. Il souligna les deux.`],
[`p`,`Puis il prit les deux flacons et les remplit lui-même, à même le voile, en le pressant entre le pouce et l'index. Il les boucha, les essuya, les rangea debout dans un coin de la bassine.`],
[`p`,`Nora prit son relais et ôta le rabat en entier. La veilleuse passa autour du corps d'Eliott et décolla ce qui restait de gelée aux plis des coudes et des genoux.`],

[`pause`,`· · ·`],

[`p`,`De la même manière, Andrew replia le second rabat d'un quart et l'arrêta là.`],
[`p`,`Ce corps-là mit plus longtemps à revenir. Une quarantaine d'années, et pour une fois personne ne se trompa de beaucoup. Il ouvrit les yeux, les referma, les rouvrit, et regarda le plafond très haut sans rien y chercher.`],
[`p`,`Eliott observait la scène tandis que Nora s'affairait autour de lui. Il regardait ce qu'on faisait à l'autre. Les mains sur l'épaule, le voile qui venait d'un tenant, le miroir qu'on tournait. Il regardait comme on regarde quelqu'un subir la chose qu'on vient soi-même de subir, avec cet intérêt un peu bête qu'on y met.`],
[`p`,`Nora tendit les mains. Le garçon les prit et sortit tout seul, les jambes hésitantes, et elle le tint le temps qu'il fallait. Elle lui passa par la tête une serviette de cérémonie — un grand rectangle de toile percé d'un trou, qui tombait droit devant et droit derrière — croisa les pans sur les côtés et les ferma d'une ceinture.`],
[`p`,`Le garçon brisa les murmures en une phrase.`],
[`tiret`,`— Il faut vider mes poches.`],
[`p`,`Personne ne répondit. Il ne regardait personne en particulier, et il attendait vraiment qu'on fasse quelque chose.`],
[`tiret`,`— Elles sont pleines.`],
[`p`,`Deux ou trois personnes regardèrent la serviette, comme s'il avait pu y avoir des poches dessus. Il n'y avait rien. Une femme, au milieu du mur, avait posé la main sur le bras de son voisin sans s'en apercevoir.`],
[`p`,`Andrew ne se retourna pas. Il avait les deux mains occupées à prélever la gelée sur le corps de l'homme.`],
[`p`,`Puis le garçon reprit, plus doucement, comme on rassure quelqu'un :`],
[`tiret`,`— Je reviens bientôt.`],
[`p`,`Nora marqua un temps. Un seul.`],
[`tiret`,`— Ça arrive, dit-elle, pour la salle. Ça arrive souvent.`],
[`p`,`Et c'était vrai. Les arrivants sortaient avec la langue et rien d'autre, et la langue tournait à vide un moment avant de se poser sur quelque chose. Il n'y avait rien à comprendre ; juste à attendre. Ce n'était pas systématique.`],
[`tiret`,`— Non non, tu ne comprends pas, c'est un peu tard !`],
[`p`,`La veilleuse eut un léger mouvement de tête étonné, sauvé par un sourire rassurant. Elle rajusta sa serviette qui n'en avait pas besoin et l'installa à table.`],
[`p`,`Il rouvrit la bouche, la referma. Et ce fut tout.`],

[`pause`,`· · ·`],

[`p`,`Andrew sortit l'instrument, fit le relevé, et trancha pour tous.`],
[`tiret`,`— Capsule éclaircie, arrivant réactif. L'Archiviste lui a compté quarante-deux ans.`],
[`p`,`Le miroir pivota. L'homme se vit dedans. Il regarda longtemps, lui aussi.`],
[`p`,`Puis on lui posa la même question qu'au garçon.`],
[`tiret`,`— Nicolas.`],
[`p`,`La voix sortit grave et éraillée, et elle le surprit autant que les autres.`],
[`p`,`Andrew s'éloigna et vint se placer près du pichet. Son travail aux postes s'arrêtait là.`],
[`p`,`Sa collègue finit tout ce qu'il y avait à faire, aida le quadragénaire à sortir et le dirigea vers la table, à la place voisine. Il posa les mains à plat devant lui parce qu'il ne savait pas quoi en faire.`],
[`p`,`Puis il tourna la tête.`],
[`p`,`Eliott le regardait déjà.`],
[`p`,`L'homme leva la main et se toucha la bouche, du bout des doigts, comme on vérifie une chose qu'on vient de voir. Eliott leva la main et se toucha la bouche.`],
[`p`,`Il fit descendre l'index le long de son menton. Eliott fit descendre le sien.`],
[`p`,`Il ouvrit la paume devant lui et la regarda. Eliott ouvrit la sienne.`],
[`p`,`Quelqu'un rit tout bas contre le mur. C'était drôle, ce petit qui singeait l'autre, et la salle avait besoin de rire de quelque chose.`],
[`p`,`L'homme s'aperçut de ce qui se passait et s'arrêta. Eliott s'arrêta aussi, la main en l'air, puis il la reposa sur la table.`],
[`p`,`Ça dura le temps que ça dura, et il tira sur sa serviette parce qu'elle glissait de l'épaule.`],
[`p`,`À ce moment-là, Andrew refermait la bassine.`],

[`pause`,`· · ·`],

[`p`,`Andrew prit le pichet et fit le tour de la table. Il versa de l'eau dans chacun des verres et les recentra en face de chaque arrivant. Il récupéra le reste et le rapporta à la desserte.`],
[`p`,`Ils burent tous les deux.`],
[`p`,`Après le nom, le pichet. C'était l'usage, et personne n'aurait su dire depuis quand : on disait que la première eau emportait ce qui restait du sommeil, et que personne ne pouvait aller le chercher à sa place. Ceux qui n'y croyaient pas regardaient quand même — c'est le seul moment où l'on voit un corps faire une chose que personne ne lui a apprise.`],
[`p`,`L'homme reposa son verre, regarda le fond, et le reprit.`],
[`p`,`Alors la salle s'avança, et pour la première fois de la matinée il y eut du bruit.`],
[`p`,`Ils vinrent un par un déposer au milieu de la table ce qu'ils avaient apporté pour leur porter chance. Un fruit. Une boule d'osier tressée. Trois épis noués par un fil de laine rouge. Une pierre plate. Une femme posa la sienne, la regarda, et la tourna d'un quart. Elle voulait qu'elle soit dans le bon sens. Il n'y avait pas de bon sens.`],
[`p`,`Ça se penchait pour mieux voir. Ça commentait.`],
[`tiret`,`— Bienvenue, dirent plusieurs, sans s'adresser à personne en particulier.`],
[`p`,`D'autres reprirent le mot en passant derrière eux. Une main s'attarda une seconde sur une épaule et repartit.`],
[`p`,`Aucun d'eux ne les connaissait. Aucun ne les reverrait. Ça n'enlevait rien.`],
[`p`,`Eliott regardait le tas grossir au milieu de la table.`],
[`p`,`Puis les visiteurs sortirent, dans le même ordre où ils étaient entrés.`],
[`p`,`Andrew tint la porte le temps que le dernier passe, et il la referma sur eux.`],
[`p`,`Le bruit du couloir s'arrêta net.`],
[`p`,`Nora fit signe à Eliott et Nicolas de la suivre. Ils se levèrent et lui emboîtèrent le pas, vers une porte au fond de la pièce à laquelle ni l'un ni l'autre n'avait fait attention jusqu'ici.`],
[`p`,`Elle s'ouvrit sur du vert, et se referma.`],
[`p`,`Les préparateurs recouchèrent les capsules sur les chariots, chargèrent les bassines et les emportèrent. Un moment plus tard, il n'y avait plus dans la pièce que deux miroirs, deux lampes, une table avec des cadeaux dessus, et un homme debout avec un carnet.`],
[`p`,`Andrew reporta les deux arrivants en une ligne. Le jour, les deux travées, l'heure, les âges relevés, les deux mots, les deux numéros. Il écrivait vite, d'une écriture qui n'était belle nulle part ailleurs.`],
[`p`,`Sous la ligne, il y avait une case pour les observations.`],
[`p`,`Son regard remonta d'un cran, sur le mot du garçon, et redescendit dessus. La pointe de la plume effleura le papier, s'y attarda, et se releva.`],
[`p`,`Il rangea le carnet.`],
[`p`,`Il éteignit les deux lampes et sortit.`,`fin`]

  ],
  tenu: [
`<strong>Le rite entier, joué sans une ligne d'explication.</strong> Le capot, le voile, le miroir, le relevé, le nom, le numéro, la serviette, le pichet, les cadeaux. <em>Rien n'est commenté : tout est fait devant le lecteur par quelqu'un qui l'a fait mille fois.</em>`,
`<strong>Le miroir, et il rend possible la dernière page.</strong> Eliott voit son propre visage avant tout le reste. Six cents pages plus loin il dira de l'homme d'à côté : <em>« j'ai vu ses yeux, tout pareils que les miens »</em> — il ne pouvait le dire que s'il venait de voir les siens, et c'est Andrew qui a tourné le miroir.`,
`<strong>L'ordre du regard, tenu au mot près.</strong> Son visage, la salle, le plafond, la capsule voisine, puis Andrew. <em>Il ne voit Nicolas qu'à la table, quand celui-ci tourne la tête</em> — ce qui valide le <em>« je l'avais pas vu, au début. Je crois que lui non plus »</em> de l'épilogue.`,
`<strong>Le mimétisme au lieu du dévisagement.</strong> Il ne fixe pas : il fait pareil. La salle rit, ce qui la soulage de ce qui vient de se passer, et le lecteur range ça dans la curiosité. <em>Ce n'en est pas.</em>`,
`<strong>Ce qu'il dit n'a aucun sens et ne peut pas être décodé.</strong> Des poches qui n'existent pas, un retour annoncé à personne. <em>Rien ne se rattache au jour de sa mort, et c'est ce qui protège l'épilogue.</em>`,
`<strong>Le narrateur se fait contredire.</strong> Il pose la règle du monde — <em>« il n'y avait rien à comprendre ; juste à attendre »</em> — et le garçon répond « non non, tu ne comprends pas ». <strong>Il a raison sur le monde et tort sur celui-là, et il ne le saura jamais.</strong>`,
`<strong>Andrew a le dos tourné pendant la seule phrase qui compte.</strong> « Je reviens bientôt » tombe pendant qu'il a les deux mains dans une capsule.`,
`<strong>La case des observations.</strong> Une plume qui effleure le papier et se relève. <em>C'est le seul endroit du chapitre où quelque chose reste en suspens, et personne ne le nomme.</em>`,
`<strong>La manie de compter, plantée en page une.</strong> Vingt-deux chaises qu'il n'a pas décidé de compter, dix-sept visiteurs, sept éléments sur la table — et <em>« il compta les petits en traversant. Ils étaient quarante-deux »</em> à la dernière page du livre.`
  ],
  ouvre: [
`<strong>Est-ce que le lecteur se souviendra du mimétisme à l'épilogue ?</strong> <em>Rien ne pèse, personne ne relève, et c'est voulu</em> — mais il faut qu'il ait quelque chose à retrouver six cents pages plus loin. <strong>C'est la vraie question ouverte du chapitre.</strong>`,
`<strong>La phrase d'accueil est donnée entière ici</strong> — <em>« Bienvenue à toi »</em> — alors qu'à sa propre cérémonie Andrew n'en attrapera que le début. À confirmer : c'est gratuit, mais il faut le vouloir.`,
`<strong>La case des observations, à garder ou à couper.</strong> C'est le seul gramme du chapitre.`,
`<strong>Le numéro n'est pas écrit en toutes lettres.</strong> Sa forme n'est fixée nulle part dans le dossier, et le texte le contourne pour l'instant.`
  ],
  note: `🔒 <strong>VERROUILLÉ — validé par l'autrice le 20 août 2026.</strong> <em>Ce texte ne bouge plus, sauf demande explicite de sa part.</em> <strong>La fabrication de l'atelier vérifie son empreinte et refuse de tourner s'il a changé.</strong>

Écrit avec l'autrice les 17 et 18 août 2026, en une dizaine de passes. <strong>Une matinée de travail ordinaire dans un lieu qu'on ne comprend pas.</strong> <em>Le système entier passe là sans un mot d'explication : un homme prépare une salle, ouvre deux capsules, note deux lignes, et éteint les lampes.</em> La quatrième version du prologue, et la première qui parte de la cérémonie d'Eliott.`
},{
  id: `chapitre-1`,
  rang: `Chapitre premier`,
  titre: `Une journée à la ruche`,
  scene: `capsule`,
  sous: `La ruche traversée d'un bout à l'autre · point de vue d'Andrew · écrit avec l'autrice le 19 août 2026`,
  p: [

[`p`,`Quatre cent trente-huit.`],
[`p`,`C'était le nombre de pas qui séparaient sa porte de celle de la ruche. Il ne l'avait jamais compté exprès : le chiffre était venu tout seul, un matin, et il n'était jamais reparti. Les jours où une voiture se garait en travers du trottoir, il en faisait quatre cent quarante et un. Ces matins-là ne comptaient pas.`],
[`p`,`La ruche s'ouvrait par deux battants de bois clair que personne ne fermait avant la nuit. Sur le montant de droite, à hauteur d'épaule, on avait taillé une capsule de profil, d'un seul trait. Tant de mains l'avaient touchée en entrant qu'elle n'était plus qu'un creux. Andrew y posa la sienne sans y penser, comme les autres.`],
[`pause`,`· · ·`],
[`p`,`Tout de suite en entrant, sur la gauche, l'accueil.`],
[`p`,`C'était une grande pièce rectangulaire, basse de plafond, la seule du complexe qui eût quelque chose de familier. On y trouvait un guichet derrière une vitre, quelques chaises alignées contre les murs et d'autres disposées dos à dos au centre de la pièce. Dix-huit visiteurs attendaient qu'on vienne les chercher. Deux d'entre eux gardaient sur les genoux ce qu'ils avaient apporté avec eux, refusant, pour une raison ou pour une autre, de le poser à leurs pieds.`],
[`p`,`Tous savaient qu'il faudrait attendre. Une cérémonie ne commence pas parce que ceux qui doivent y assister sont arrivés.`],
[`p`,`Alors chacun s'occupait comme il pouvait. De petits groupes s'étaient formés, trois ou quatre personnes tout au plus, et les conversations flottaient dans la pièce à cette hauteur de voix que personne n'a besoin de demander. On échangeait des suppositions sur la salle où l'on serait envoyé, sur le nombre de personnes qui viendraient ensuite, sur l'âge qu'on leur donnerait, sur ce qu'on allait voir entrer.`],
[`p`,`Chez certains, l'attente commençait à se lire sur les visages.`],
[`p`,`Près de la porte du fond, quatre visiteurs la regardaient toutes les deux minutes.`],
[`p`,`La pièce, pourtant, avait été pensée pour rendre l'attente supportable. Aux deux extrémités, de grandes plantes s'élevaient le long de troncs fins qui semblaient avoir poussé avec elles. Leur feuillage, plus dense à la base, s'ouvrait ensuite en larges feuilles retombant de part et d'autre.`],
[`p`,`Sur les murs, des tableaux de marqueterie. De fines feuilles de bois, choisies dans des essences différentes, découpées puis assemblées bord à bord jusqu'à ce que les joints disparaissent. Rien n'était peint. Les couleurs appartenaient au bois : ses blonds, ses bruns, ses noirs, ses veines qui devenaient parfois presque des lignes de dessin.`],
[`p`,`Ceux-là montraient des montagnes qui n'existaient nulle part. Des versants blonds sous des ombres presque noires, des ciels parcourus de veines qu'aucun ciel n'avait jamais eues. La matière faisait le paysage autant qu'elle le représentait.`],
[`p`,`On s'arrêtait parfois devant sans savoir ce qui avait retenu le regard — le paysage, le bois, ou la manière dont l'un était devenu l'autre.`],
[`p`,`Des appliques diffusaient une lumière jaune orangé, douce sans être faible.`],
[`p`,`Et, au fond de la pièce, une sculpture de verre s'élevait presque jusqu'au plafond. De minces filets d'eau coulaient le long de ses deux faces et disparaissaient dans un bassin qu'on distinguait à peine.`],
[`p`,`C'était le seul bruit continu de la salle.`],
[`p`,`L'eau.`],
[`p`,`Anna, la secrétaire, leur avait expliqué comment ça allait se passer. Elle le referait pour ceux qui arriveraient en retard, et elle le referait encore pour ceux qui n'avaient rien retenu la première fois, parce qu'il y en avait toujours un ou deux qui avaient la tête dans les nuages, tant le moment était un rendez-vous attendu.`],
[`p`,`Il longea le comptoir, en poussa le portillon et prit lui-même sa feuille dans un casier. Du côté des chaises, il y eut ce petit temps d'arrêt qu'on a lorsqu'un médecin traverse sa propre salle d'attente sans s'y asseoir.`],
[`tiret`,`— Bonjour Anna.`],
[`tiret`,`— Bonjour toi. Salle 2, ils sont quatre aujourd'hui. Nora descend à dix heures.`],
[`tiret`,`— Quatre.`],
[`tiret`,`— Quatre. Tu es en avance de deux minutes.`],
[`tiret`,`— Je suis toujours en avance de deux minutes.`],
[`tiret`,`— Je sais. C'est pour ça que je le dis.`],
[`p`,`Il rit. C'était la même plaisanterie depuis des années et elle marchait encore.`],
[`p`,`Le veilleur plia la feuille en deux et la glissa dans la poche basse de sa blouse. Il quitta l'accueil et s'engagea dans un grand couloir.`],
[`pause`,`· · ·`],
[`p`,`Les dix-huit, eux, ne prendraient pas ce chemin. On viendrait les chercher dans la salle d'attente, puis on les ferait sortir par l'autre côté. De là, ils traverseraient la zone de résidence avant de rejoindre la porte qui leur était destinée.`],
[`p`,`Cette partie du complexe était réservée aux arrivants. Après l'examen de la cueillie — le tout premier examen de leur vie —, ils y resteraient huit jours au minimum. Des chambres, un réfectoire, et quelques visiteurs chargés de leur tenir compagnie pendant ce qui pouvait ressembler, vu de l'extérieur, à une période de repos.`],
[`p`,`La première inspection avait un but simple : s'assurer que l'arrivant était bien arrivé immaculé, sans anomalie ni blessure.`],
[`p`,`On n'était jamais trop prudent.`],
[`p`,`D'après les études menées jusque-là, toutes les capsules n'avaient pas les mêmes délais de maturation. Il arrivait même que, d'une travée à l'autre, leur maturation s'achève sur des relevés étranges. Dans ces cas-là, on vérifiait que l'arrivant n'avait pas été touché d'une manière ou d'une autre au cours du processus.`],
[`p`,`Cette vérification revenait à l'analyste.`],
[`p`,`Ils étaient hommes et femmes, tous experts dans leur domaine, et passaient déjà leurs journées à étudier les capsules, leurs mesures et leurs variations. Il n'y avait donc rien d'étrange à ce qu'ils examinent également ce qui en sortait.`],
[`p`,`C'était, au fond, la même chose.`],
[`p`,`Du moins, c'était ainsi qu'on le présentait.`],
[`p`,`Le couloir était large et linéaire, avec un plafond bas et des appliques disposées tous les six mètres. Pendant vingt pas, on aurait pu se croire dans n'importe quel bâtiment administratif du pays.`],
[`p`,`Puis le plafond montait.`],
[`p`,`Il montait d'un coup, et continuait de monter.`],
[`p`,`À mesure qu'il s'élevait, les lampes devenaient inutiles. On ne les éteignait pas — personne n'avait jamais reçu l'ordre de le faire — mais quelque chose de plus grand qu'elles arrivait par le haut. Le jour tombait de très loin, en longues obliques. Sur les dalles, il déposait des plaques claires que l'on pouvait traverser ou contourner.`],
[`p`,`Andrew les traversait.`],
[`p`,`On n'était pas dehors. On n'était jamais dehors, ici. Tout tenait sous un seul toit, et ce toit était si haut qu'on avait cessé d'y penser.`],
[`p`,`Les murs, eux, étaient sculptés.`],
[`p`,`Pas décorés : sculptés.`],
[`p`,`Du sol jusqu'à la hauteur où le regard renonce, des bandes horizontales couraient sur toute la longueur, l'une au-dessus de l'autre. Dans chacune, une scène minuscule qu'il aurait fallu s'arrêter pour lire. Des entrelacs s'intercalaient entre les bandes. Des signes revenaient tous les trois mètres, et plus personne ne connaissait leur valeur. Derrière tout cela, taillé plus profondément dans la pierre, un second plan n'apparaissait qu'en biais, lorsque le jour tombait du bon côté.`],
[`p`,`Ce n'était pas de la magie.`],
[`p`,`Ce patrimoine n'avait pas surgi de nulle part du jour au lendemain, et personne n'avait jamais prétendu le contraire. Seulement, on n'avait jamais su de quelle génération l'idée était venue.`],
[`p`,`Et par-dessus, la végétation courait.`],
[`p`,`Elle avait l'air libre, mais elle ne l'était pas tout à fait. On avait bâti là où l'on pouvait bâtir, ce qui supposait qu'on avait regardé avant. Ensuite, on s'était adapté.`],
[`p`,`Jamais un coulant n'avait été coupé pour faire passer un mur.`],
[`p`,`Lorsqu'un coulant passait, on perçait le mur et on continuait de l'autre côté. Il y avait des trous partout, ronds et propres, avec un brin vert au milieu, et personne ne trouvait cela remarquable.`],
[`p`,`À mi-parcours, une porte sur la droite ouvrait sur la salle de repos. Une odeur de café s'en échappait, mêlée à des voix qui se coupaient la parole. Il reconnut celle de Nora.`],
[`p`,`Il ne s'arrêta pas pour autant.`],
[`pause`,`· · ·`],
[`p`,`Puis le couloir cessa.`],
[`p`,`Il ne donnait pas sur une pièce. Il donnait sur un volume.`],
[`p`,`Le sol changeait, la lumière aussi. L'air était plus lourd de deux ou trois degrés. La coulée prenait tout : les murs, l'espace entre les colonnes, la traversée du vide, du sol jusqu'à des hauteurs où personne n'était jamais monté vérifier.`],
[`p`,`Et sur la coulée, les capsules.`],
[`p`,`Il y en avait partout, et jamais deux fois au même endroit.`],
[`p`,`Une à hauteur de hanche, sur un coulant qui rampait le long d'un banc. Une autre à six mètres, seule, accrochée à une branche qui traversait le vide. Puis, dix pas plus loin, six collées les unes aux autres sur deux mètres, si serrées qu'il faudrait les décrocher dans l'ordre.`],
[`p`,`Elles poussaient à plat, couchées sur ce qui les portait.`],
[`p`,`Jeunes, elles avaient la couleur de la coulée. Puis elles la perdaient en mûrissant, jusqu'à prendre, à la fin, ce jaune orangé, presque translucide, qui indiquait qu'elles étaient prêtes.`],
[`p`,`Pour aller chercher celles qui poussaient en hauteur, on montait des échafaudages. On les redescendait ensuite.`],
[`p`,`C'était la serre.`],
[`p`,`Très haut, sur une plateforme montée la veille, trois préparateurs travaillaient autour d'une capsule considérée comme arrivée à maturité. Deux la tenaient par-dessous pendant que le troisième la détachait. Ils ne l'auraient pas fait hier et ils ne le feraient pas demain : l'analyste avait donné le jour, et c'était aujourd'hui. On appelait ça la cueillie. L'heure serait notée, et elle finirait sur la fiche qu'on remettrait au veilleur.`],
[`p`,`Au loin, immanquable, la porte du registre. Massive, elle aussi tout autant chargée d'ornements que le reste, encadrée de chaque côté par le mur de pierre qui faisait le tour de la salle, et la coulée serpentant dessus par endroits. Il n'allait pas là non plus.`],
[`p`,`Les différents quartiers, eux, se fondaient dans l'environnement de la serre. Des murs, un toit, une porte, sculptés comme tout ce qui avait été bâti ici, et la coulée qui passait entre eux et par-dessus.`],
[`p`,`Un préparateur répondant au nom de Bastien reconnut le veilleur de loin, à sa silhouette et à sa façon de marcher.`],
[`p`,`Andrew était grand sans être imposant, l'épaule large, la taille droite, avec la solidité tranquille de ceux qui entretiennent leur condition sans chercher à paraître plus forts qu'ils ne le sont. Cheveux bruns, courts, légèrement désordonnés, deux ou trois mèches refusant de rester en place — et quelques autres restées blanches. Barbe courte, mâchoire carrée, nez droit, sourcils épais. Les yeux d'un brun profond, attentifs, toujours en train d'observer quelque chose : chaleureux quand il se détendait, nettement plus sérieux dès qu'il se concentrait. Rien d'intimidant au premier regard. Ce n'était pas une raison pour le sous-estimer.`],
[`p`,`Cinquante-deux ans. Dix ans de service.`],
[`p`,`Il portait la tenue, comme tout le monde ici : blouse de toile écrue, croisée sur le devant, six boutons sur le côté droit, l'écusson brodé sur l'épaule opposée, deux poches basses. La ceinture au septième trou en partant du bout. Le petit clic tombait toujours au même endroit. Pas six, pas huit.`],
[`p`,`Ses chaussures étaient la seule chose à lui.`],
[`p`,`Bastien traversa pour le rejoindre. Il venait de la coulée et ça se voyait : manches roulées, avant-bras verts jusqu'au coude, et cette odeur de tige coupée que les gens de la serre traînent partout et ne sentent plus.`],
[`tiret`,`— Andrew ! Tu tombes bien.`],
[`tiret`,`— C'est ce qu'on me dit tous les matins, et ça n'a jamais rien annoncé de bon.`],
[`tiret`,`— J'ai un problème de compte. Tu as deux minutes ?`],
[`tiret`,`— J'ai deux heures.`],
[`pause`,`· · ·`],
[`p`,`Le quartier des préparateurs s'ouvrait sur une allée centrale, assez large pour y faire passer deux chariots de front, et de chaque côté des boxes où l'on travaillait. Pas de portes : des cloisons à mi-hauteur, un établi par box, des crochets partout. Des caisses empilées contre le mur du fond, quatorze. Sur la cloison de droite, un tableau noir couvert de numéros de travées, effacé et réécrit tant de fois que le noir était devenu gris.`],
[`p`,`Ils étaient une quinzaine, et il n'y avait pas de bureaux.`],
[`p`,`Deux ou trois levèrent la main en le voyant entrer. On lui proposa du café et il accepta de bon cœur. Il n'avait pas fait le détour par la salle de repos ; ce n'était pas une raison pour refuser une bonne tasse.`],
[`p`,`Dans le premier box, sur l'établi, une capsule. Cueillie dans la nuit, calée sur deux berceaux de mousse, avec deux personnes autour. L'une lavait la paroi au chiffon, à l'eau claire, en tournant toujours dans le même sens, et l'eau du seau était verte. L'autre avait décollé le rabat sur dix centimètres, glissé dessous trois sondes souples, et rabattu par-dessus. Les sondes remontaient jusqu'à un appareil posé au bout de la table, une caisse grise avec un cadran et deux aiguilles qui ne bougeaient presque pas.`],
[`p`,`C'était la dernière chose qu'on faisait à une capsule. Après ça, elle ne serait plus touchée que par un veilleur.`],
[`tiret`,`— Elle est pour toi, celle-ci, non ? dit le préparateur au chiffon.`],
[`tiret`,`— Salle 2. À dix heures.`],
[`tiret`,`— Elle est belle.`],
[`tiret`,`— Elles sont toutes belles.`],
[`tiret`,`— Celle-là, ce n'est pas pareil. Regarde-la.`],
[`p`,`Il la regarda. Elle était belle.`],
[`p`,`L'homme au chiffon s'émerveillait devant une capsule comme quelqu'un qui n'en aurait jamais vu.`],
[`tiret`,`— On ne t'en a pas montré, à l'école ? dit Andrew.`],
[`tiret`,`— Oh si, si. Mais ce n'est pas la même chose que de les voir en vrai !`],
[`p`,`« Capsule éclaircie, arrivant réactif. L'Archiviste lui a compté soixante-seize ans », se souvint Andrew en considérant son sourire béat.`],
[`p`,`Personne ne pouvait lui en vouloir. Il avait encore des cours du soir, et ça faisait à peine un mois qu'il était là. Un apprenti modèle, qui apprenait vite.`],
[`p`,`Dans ce service — comme partout ailleurs — les plus anciens du métier étaient aussi ceux qui avaient l'air les plus jeunes. Ça se comprenait très bien.`],
[`p`,`Vera arrivait derrière eux. En tant qu'analyste, elle se pencha sur le cadran, le regarda deux secondes et ne dit rien. Elle continua jusqu'au fond de la pièce, où l'attendaient un tabouret trop haut pour sa table et l'ensemble de ses planches.`],
[`p`,`Quand l'analyste tranchait, elle avait raison. Ce n'était pas une affaire de grade — personne dans ce bâtiment ne commandait à personne. C'était son métier, et rien d'autre. La maturation d'une capsule, elle l'avait apprise par cœur, année après année, relevé après relevé. Observer, reconnaître, comparer, prédire. Le préparateur cueillait, lavait, branchait et conduisait ; il écoutait la date qu'on lui donnait, il l'acceptait sans discuter, et il avait cent fois raison de le faire.`],
[`tiret`,`— La dix-neuf, dit Bastien.`],
[`tiret`,`— La travée dix-neuf ?`],
[`tiret`,`— Oui. Elle a douze capsules.`],
[`p`,`Vera ne leva pas la tête tout de suite.`],
[`tiret`,`— Elle en a onze.`],
[`tiret`,`— Ça, c'était avant. Maintenant il y en a douze. Je suis allé les recompter trois fois.`],
[`p`,`Elle posa son crayon et sortit sa planche de la travée dix-neuf. Onze colonnes, onze séries, onze histoires commencées à onze dates différentes. La douzième n'était nulle part. Elle n'avait jamais été relevée, parce que personne n'avait jamais su qu'elle était là.`],
[`tiret`,`— Elle est où ?`],
[`tiret`,`— Tout au fond, au ras du sol, sous les autres. On ne la voit qu'accroupi. Je ne descends pas là toutes les semaines.`],
[`tiret`,`— Depuis quand ?`],
[`tiret`,`— Aucune idée.`],
[`p`,`Andrew écoutait sans rien dire. Ça n'avait rien d'extraordinaire : une capsule pousse où elle pousse, personne n'a jamais choisi l'emplacement d'une seule d'entre elles, et il y en avait des dizaines de milliers dans ce bâtiment. On en oubliait. On les retrouvait.`],
[`tiret`,`— Tu l'as touchée ? dit Vera.`],
[`tiret`,`— Oui.`],
[`tiret`,`— Et ?`],
[`tiret`,`— Elle est prête.`],
[`p`,`Une main de préparateur ne valait pas celle d'une analyste. Bien sûr qu'elle pouvait sembler prête. Ce n'était pas si simple que ça.`],
[`p`,`Le geste seul ne donnait pas de date. Vera pouvait relever cette capsule dans l'heure, elle n'aurait qu'un point sur un graphique vierge, et il en fallait quatre au minimum pour chiffrer correctement le jour d'une éclaircie totale. Toutes les capsules n'arrivaient pas à maturation de la même manière. C'était en croisant des moyennes, des chiffres accumulés sur des années et les relevés faits sur place qu'on finissait par le savoir.`],
[`p`,`Or Bastien pouvait se tromper comme ne pas se tromper. Il était nouveau dans le métier, et un préparateur ne tranchait pas. Tout le monde le pensait tout bas sans le dire tout haut. Personne ne lui en voulait de ne pas savoir encore.`],
[`tiret`,`— Deux jours, dit-elle. Avant ça, je ne dirai rien. De toute manière, si ça avait été une capsule flash, elle se serait ouverte depuis longtemps.`],
[`tiret`,`— Mais elle est claire, dit Bastien.`],
[`tiret`,`— Je ne dis pas le contraire.`],
[`p`,`Andrew regarda le tableau noir. Trois travées avaient une salle en face : la neuf, la dix, la onze. Trois salles, trois veilleurs. En face de la dix-neuf, celle de Bastien, il n'y avait rien — on ne réserve pas une salle pour une capsule qui n'existe sur aucune planche.`],
[`p`,`Une capsule qui s'ouvre sans personne autour s'ouvre quand même. Elle n'attend pas, elle ne prévient pas. C'était arrivé deux fois depuis qu'il était là, et les deux fois quelqu'un s'était retrouvé debout tout seul au milieu de la coulée, sans miroir, sans eau, sans personne à qui donner son nom.`],
[`tiret`,`— Je relèverai deux fois par jour, dit Vera. Matin et soir. Et je veux qu'on recompte tout le fond avant la fin de la semaine.`],
[`tiret`,`— Ça va prendre trois jours.`],
[`tiret`,`— Ça prendra trois jours.`],
[`p`,`Andrew sortit son carnet.`],
[`tiret`,`— Je passerai la voir aussi.`],
[`tiret`,`— Quand ?`],
[`tiret`,`— Le matin. Avant de descendre.`],
[`p`,`Il écrivit : travée dix-neuf, douzième capsule, et la date et l'heure qu'il était.`],
[`p`,`Il n'avait pas d'avis sur la date et il n'en aurait pas. C'était le confort du métier : les autres prévoyaient, lui constatait.`],
[`tiret`,`— Et si elle s'ouvre cette nuit ? dit Vera.`],
[`tiret`,`— Alors elle s'ouvrira cette nuit, et on n'y pourra rien.`],
[`p`,`C'était vrai, ça ne consolait personne, et les trois s'en contentèrent parce qu'il n'y avait rien d'autre à en tirer.`],
[`tiret`,`— Tu descends où, aujourd'hui ? demanda Bastien en le raccompagnant jusqu'à la porte.`],
[`tiret`,`— Salle 2. Ils sont quatre.`],
[`tiret`,`— Quatre, répéta Bastien, avec le petit hochement de tête qu'on a pour les bonnes nouvelles des autres. Alors c'est un bon jour.`],
[`tiret`,`— C'est déjà ce qu'on m'a dit ce matin.`],
[`pause`,`· · ·`],
[`p`,`Il ressortit et prit à gauche, vers l'aile des cérémonies.`],
[`p`,`Il n'avait rien à porter. On avait descendu la veille ce qu'il fallait dans la salle 2 : la nappe et le chemin de table, les serviettes dans les quatre tailles, les timbales, les flacons vides. On le faisait pour lui, il le faisait pour d'autres, et personne ne tenait le compte.`],
[`p`,`L'odeur le prit à cinquante mètres.`],
[`p`,`Elle n'arrivait pas de face. Elle était déjà là, installée dans l'allée, sans direction, comme une température. Il aurait pu faire le tour par l'autre côté. Il ne le fit pas, parce qu'il était en avance et parce qu'on ne change pas de chemin pour une odeur.`],
[`pause`,`· · ·`],
[`p`,`Ils étaient quatre au bout de l'allée, en combinaison.`],
[`p`,`Trois regardaient. Le quatrième raclait.`],
[`tiret`,`— Ouais, et surtout le fond ! On laisse rien, faut que ça brille ! criait l'un.`],
[`p`,`Les autres riaient, et celui qui raclait riait aussi, parce que c'était son tour et qu'il n'y avait rien à dire.`],
[`p`,`C'était le dernier entré au service. C'était aussi le seul à qui on aurait donné soixante ans.`],
[`p`,`Andrew le regarda le temps de passer et ne trouva rien à en dire.`],
[`p`,`On disait de celles-là que c'étaient des capsules non éclaircies. C'était le mot du registre, et ce n'était pas celui des yeux.`],
[`p`,`Ça ne ressemblait pas à une capsule. Ça n'en avait ni la longueur, ni les nervures, ni cette dissymétrie propre aux choses qui ont poussé. C'était une poche sombre et boursouflée, sortie de travers sur un coulant de bordure.`],
[`p`,`Personne ne l'avait vue grossir et personne n'aurait pu la relever. Elle était venue d'un coup, puis avait crevé dans la nuit, sur le flanc, sans que rien l'annonce.`],
[`p`,`On aurait dit une excroissance que la coulée s'était faite à elle-même, puis qu'elle avait poussée à l'écart pour ne pas salir ce qu'il y avait autour.`],
[`p`,`Il en restait ça : quelque chose d'affaissé sur le coulant, comme un sac qu'on aurait vidé sans le poser.`],
[`p`,`Le reste avait coulé.`],
[`p`,`Ce n'était pas de la gelée. La gelée est orange, mate, sèche ; elle s'enlève d'un tenant et ne laisse rien derrière elle.`],
[`p`,`Ça, c'était autre chose.`],
[`p`,`Ça s'était étalé sur trois mètres et avait pris la pente. Par endroits, c'était encore en tas, avec des grumeaux gros comme le poing, plus pâles au cœur, qui gardaient un moment la marque de la raclette avant de se refermer lentement dessus.`],
[`p`,`Ailleurs, c'était plus clair, plus liquide, et ça s'était insinué dans le joint entre deux dalles. Il faudrait revenir gratter demain.`],
[`p`,`Entre les deux, il y avait tout ce qu'on veut : des filaments qui pendaient au bord du seau lorsqu'on relevait l'outil et ne se décidaient pas à tomber ; une membrane formée en surface qui se plissait quand on marchait à côté ; et, dessous, la masse qui continuait de descendre parce que le sol descendait.`],
[`p`,`Les régurgitations de n'importe quel être vivant, petit ou grand, à côté de ça, c'était du petit-lait.`],
[`p`,`Les seaux étaient alignés le long du mur, à moitié pleins.`],
[`p`,`Il y en avait six.`],
[`p`,`Il en faudrait un septième.`],
[`tiret`,`— La cinquième cette semaine, dit quelqu'un derrière.`],
[`p`,`Personne ne répondit.`],
[`p`,`Il n'y avait rien à répondre, et il restait deux mètres à faire.`],
[`p`,`On nettoyait vite. Pas pour l'odeur : parce qu'on disait qu'une travée gâtée gâtait ses voisines. Personne n'avait jamais vérifié si c'était vrai, et personne ne tenait à être celui qui essaierait.`],
[`p`,`Andrew n'y toucha pas.`],
[`p`,`Il l'avait fait pendant deux ans, comme tout le monde, et depuis, d'autres le faisaient. Il ne ralentit pas et ne se boucha pas le nez, parce qu'aucun des quatre ne l'aurait fait à sa place et qu'on se tient droit devant les gens qui travaillent.`],
[`p`,`Il passa à trois mètres et continua vers la salle 2, où quatre capsules s'apprêtaient à être redressées pour dix heures précises, claires et propres, sur leurs chariots.`],
[`p`,`L'odeur le suivit dans l'allée. Une odeur, insipide, et prenante au nez, comme le fond d'un vase de fleurs qu'on aurait oublié tout un été.`,`fin`],
  ],
  tenu: [
`<strong>Le complexe donné par quelqu'un qui y va travailler.</strong> L'accueil, le grand couloir, le basculement de la lampe au jour, la serre, les quartiers bâtis dedans. <em>Personne n'explique rien.</em>

<strong>Et le chemin des visiteurs, dit en trois lignes et jamais emprunté :</strong> l'autre côté, la zone de résidence, la bonne porte. <em>C'est là que le mot analyste entre dans le livre — et qu'on apprend qu'il joue sur deux tableaux : le corps des arrivants, puis ses planches.</em>`,
`<strong>On voit enfin une capsule pousser.</strong> Partout, jamais deux fois au même endroit, onze collées les unes aux autres à un endroit et une seule à six mètres ailleurs. <em>Et personne n'a jamais choisi l'emplacement d'une seule d'entre elles.</em>`,
`<strong>La cueillie se fait devant le lecteur</strong>, sur un échafaudage, à trois, à la main. <em>On ne guette pas une capsule : une analyste a donné le jour, et c'est aujourd'hui.</em> L'heure finit sur la fiche que le prologue faisait passer au veilleur.`,
`<strong>Le mot serre arrive après la chose, et il ne s'explique pas.</strong> <em>Le volume, la coulée qui prend tout, les capsules partout, les échafaudages — puis trois mots : « C'était la serre. »</em> Le lecteur a déjà tout vu ; le mot ne fait que ranger ce qu'il vient de voir.`,
`<strong>Les passerelles sont la seule chose laide du complexe.</strong> Personne n'a jamais proposé de faire autrement.`,
`<strong>Le bâti est des anciens, la végétation est à elle.</strong> Aucun coulant n'a jamais été coupé pour faire passer un mur : on perce le mur, on continue de l'autre côté, <em>et personne ne trouve ça remarquable.</em>`,
`<strong>Le portrait d'Andrew, sur un regard de loin.</strong> <em>La manie ne se nomme jamais : quatre cent trente-huit, neuf, quatorze, cinquante-deux, dix, sept, six seaux et un septième.</em>`,
`<strong>La capsule d'Andrew est préparée sous ses yeux</strong> — lavée, sondée, branchée, vérifiée par l'analyste au passage. <em>« Elles sont toutes belles. » « Non. Regarde-la. » Il la regarda. Elle était belle.</em>`,
`✅ <strong>Ce n'est pas un conflit, c'est une information.</strong> <em>Décision de l'autrice, 19 août 2026 : le préparateur n'a pas à tenir tête à l'analyste, c'est elle qui a le dernier mot.</em> <strong>Alors il ne la contredit pas : il lui apprend qu'il y a une capsule de plus.</strong> Chacun fait son métier et personne n'a tort.`,
`<strong>La douzième capsule de la travée dix-neuf n'est sur aucune planche.</strong> Jamais relevée, parce que personne n'avait jamais su qu'elle était là — au ras du sol, sous les autres, <em>on ne la voit qu'accroupi.</em>

<strong>Et l'enjeu tombe tout seul :</strong> une main dit qu'elle est prête, une série ne se lit pas avant quatre relevés, et une salle ne se réserve pas pour une capsule qui n'existe nulle part. <em>Une capsule qui s'ouvre sans personne autour s'ouvre quand même : c'est arrivé deux fois, et les deux fois quelqu'un s'est retrouvé seul au milieu de la coulée, sans miroir, sans eau, sans personne à qui donner son nom.</em>`,
`<strong>Andrew paie la différence de sa poche.</strong> Vingt minutes chaque matin, qu'il appelle <em>rien du tout</em>. Personne ne le remercie et le lecteur l'a vu.`,
`<strong>Les autres prévoyaient, lui constatait.</strong> Dit une fois, en passant, sans nommer le registre — <em>il n'a pas encore été présenté, et surtout il n'annonce rien.</em>

<strong>Bastien est un débutant, et personne ne le lui reproche.</strong> <em>« Or Bastien pouvait se tromper comme ne pas se tromper. Il était nouveau dans le métier, et un préparateur ne tranche pas. Tout le monde le pensait tout bas sans le dire tout haut. »</em> <strong>C'est la seule ligne du chapitre où quelqu'un est jugé, et elle est douce.</strong>`,
`🔴 <strong>L'inversion des âges tombe ici, et c'est le hook du chapitre.</strong> <em>Trouvaille de l'autrice, 19 août 2026 : le préparateur qui s'émerveille devant une capsule est un homme de soixante-douze ans qui n'en avait jamais vu.</em>

<strong>Et l'âge n'est pas donné par le narrateur : il revient dans la voix du rite, et à l'intérieur de la tête d'Andrew.</strong> <em>« Capsule éclaircie, arrivant réactif. L'Archiviste lui a compté soixante-seize ans », se souvint Andrew en considérant son sourire béat.</em> <strong>La formule n'est pas prononcée : elle remonte.</strong>

<strong>Et le mot école arrive avant, en dialogue, l'air de rien :</strong> <em>« — On ne t'en a pas montré, à l'école ? — Oh si, si. Mais ce n'est pas la même chose que de les voir en vrai ! »</em> <strong>C'est « soixante-seize ans », deux lignes plus bas, qui le fait exploser.</strong>

<strong>Puis l'excuse, qui est le coup de grâce :</strong> <em>« Personne ne pouvait lui en vouloir. Il venait tout juste de quitter les bancs de l'école et il avait encore des cours du soir. Ça faisait à peine un mois qu'il était là, un apprenti modèle qui apprenait vite. »</em>

<strong>C'est la phrase la plus tendre du chapitre, et elle dit tout le système.</strong>

<strong>C'est la formule du prologue, mot pour mot, quatre mois plus tard, sur un homme qui tient un chiffon.</strong> <em>Le lecteur l'a entendue sur un garçon de dix ans et sur un homme de quarante-deux ; il l'entend maintenant sur quelqu'un qui travaille là.</em>

⛔ <strong>Un seul âge, et aucune durée.</strong> <em>On ne dit pas depuis quand il est sorti : le lecteur voit qu'il a rajeuni et ne peut pas chiffrer de combien.</em> <strong>Deux nombres et un intervalle donneraient une vitesse, et l'interdit n° 3 tomberait dans la même phrase.</strong>

✅ <strong>Et l'école règle la vraisemblance :</strong> <em>on ne prend pas un poste en sortant de sa capsule.</em> <strong>Les bancs de l'école et les cours du soir sont les mots les plus banals du chapitre, et les plus violents.</strong>

<strong>Puis la règle du monde, énoncée à plat et jamais expliquée :</strong> <em>« Dans ce service — comme partout ailleurs — les plus anciens du métier étaient aussi ceux qui avaient l'air les plus jeunes. Ça se comprenait très bien. »</em> ⚠️ <em>Ces deux phrases sont les seules du passage qui généralisent — elles peuvent sauter, et le bizutage porterait alors la règle tout seul.</em>

⛔ <strong>Le narrateur affirme que ça se comprend et ne dit pas pourquoi.</strong> <em>Le lecteur reste avec la phrase sur les bras — et le bizutage, vingt pages plus loin, n'a plus rien à lui expliquer.</em>`,
`<strong>La capsule pourrie ne contient personne — et n'est même pas une capsule.</strong> <em>« C'était le mot du registre, et ce n'était pas celui des yeux. »</em> Ni la longueur, ni les nervures, ni la dissymétrie de ce qui a poussé : <strong>une poche sombre et boursouflée, venue d'un coup, qu'on dirait une excroissance que la coulée s'est faite à elle-même et qu'elle a poussée à l'écart.</strong> <em>Rien n'a mûri là-dedans, et c'est ce qui interdit au lecteur d'y loger quoi que ce soit.</em> Une matière, une pente, six seaux et il en faudra un septième.`,
`<strong>Le chapitre se ferme sur la formule</strong>, qui n'existera qu'à un seul autre endroit du livre.`
  ],
  ouvre: [
`✅ <strong>La formule, arrêtée.</strong> <em>« une odeur, insipide, et prenante au nez, comme le fond d'un vase de fleurs qu'on aurait oublié tout un été. »</em> — <em>le linge tiède ne marquait pas assez.</em> <strong>Celle-ci est plate, connue de tout le monde, impossible à rattacher à un corps — et c'est une odeur de plante, dans un lieu qui n'est que ça.</strong> Le jour où elle bouge, la seconde cérémonie bouge avec.`,
`✅ <strong>La dénégation est supprimée.</strong> <em>« à cause de la pente, et pas pour une autre raison » — décision de l'autrice, 19 août 2026 : ne pas l'insinuer invite à l'imaginer quand même.</em> <strong>Il ne reste que la masse qui descend parce que le sol descend.</strong>`,
`<strong>Anna, Bastien, Vera.</strong> Trois prénoms inventés pour le chapitre. <em>L'analyste reste une femme — c'est la préparatrice au chiffon qui est devenue un homme, pour qu'on ne confonde plus les deux.</em>`,
`✅ <strong>La douzième capsule n'est pas un fil.</strong> <em>Décision de l'autrice, 19 août 2026 : « je vois pas trop quoi en faire, c'est un fait qui n'apportera rien ».</em> <strong>La scène reste — c'est elle qui apprend au lecteur qui tranche et qui exécute — mais le livre ne doit plus rien.</strong> <em>Le soulignement du carnet est tombé : Andrew note, comme il note tout, et on passe.</em>`,
`<strong>Les plantes de l'accueil ne sont toujours pas nommées</strong> — <em>de larges feuilles fendues</em>.`,
`<strong>Le chapitre s'arrête avant la cérémonie</strong>, et le registre tombe avec elle. <em>À replacer ailleurs, ou à rendre à ce chapitre.</em>`,
`<strong>Andrew ne dit rien de la capsule pourrie, et ne pense rien.</strong> <em>C'est le régime demandé — reste à vérifier que ça ne le rend pas froid juste après qu'on a travaillé à le rendre chaleureux.</em>`
  ],
  note: `🔒 <strong>VERROUILLÉ — validé par l'autrice le 20 août 2026.</strong> <em>Ce texte ne bouge plus, sauf demande explicite de sa part.</em> <strong>La fabrication de l'atelier vérifie son empreinte et refuse de tourner s'il a changé.</strong>

Écrit avec l'autrice le 19 août 2026 en quinze passes, repris le 20 en une trentaine de corrections — l'accueil, le grand couloir, la serre, la capsule qui a crevé. <strong>Le deuxième chapitre du livre, et le premier où l'on voit le lieu.</strong> <em>Un homme arrive au travail, traverse la serre, discute d'une travée avec les deux métiers qui ne se prédisent pas de la même façon, repart vers sa salle — et croise en chemin une chose qu'on est en train de racler.</em> La cérémonie qu'il allait faire n'est pas dans le chapitre.`
},{
  id: `chapitre-2`,
  rang: `Chapitre deuxième`,
  titre: `L'aquarium`,
  scene: `s1`,
  sous: `Première visite chez June · point de vue d'Andrew · en cours d'écriture, 22 août 2026`,
  p: [

[`p`,`Il n'avait rien écrit dans la case.`],
[`p`,`Le carnet resta dans la poche de sa blouse toute la semaine, et les pages s'empilèrent par-dessus. Il le rouvrit un matin avant de commencer, à celle-là, pour vérifier une heure. Le jour, les deux travées, l'heure, les âges relevés, les deux mots, les deux numéros. Tout y était. Le bout de la ligne était blanc.`],
[`p`,`Il le rouvrit à la même page le mardi suivant, et il ne vérifia rien.`],
[`pause`,`· · ·`],
[`p`,`La rue montait sans qu'on s'en aperçoive et les maisons se ressemblaient toutes. Un carré d'herbe devant, une allée de gravier jusqu'au perron, une boîte aux lettres sur son piquet. Celle de June était la quatrième après le tournant, avec un cerisier qui n'avait plus rien à donner à cette saison.`],
[`p`,`Il sonna. L'attente fut courte.`],
[`p`,`June ouvrit, un torchon à la main. Blonde, les cheveux tirés en arrière et noués bas, sans que ça la durcisse. Élancée, des vêtements simples, un tablier par-dessus. Vingt-deux ans, à peu près, et berceuse.`],
[`tiret`,`— Ah, bonjour. Entrez, entrez.`],
[`p`,`Elle s'essuya les mains à son tablier et s'écarta pour le laisser passer. Elle avait la manche gauche remontée plus haut que l'autre.`],
[`tiret`,`— Il finit quelque chose là-haut, il en a pour deux minutes. Vous prendrez bien un verre d'eau, il fait une chaleur.`],
[`tiret`,`— Je veux bien.`],
[`p`,`Elle repartit vers l'évier et reprit sa vaisselle là où elle l'avait laissée. Andrew resta debout dans l'encadrement, comme les autres fois.`],
[`pause`,`· · ·`],
[`p`,`Julie était installée à la table de la salle, en face, une machine à coudre devant elle et un pantalon en travers des genoux. Châtaine, les cheveux ondulés, retenus d'un côté par une pince. Elle leva la tête, dit bonjour, et retourna à son ouvrage.`],
[`p`,`Andrew la regarda faire. Elle plia l'ourlet à l'ongle, le fit passer sous le pied de biche sans une épingle, tourna le tissu d'un quart à l'angle et repartit dans l'autre sens. Elle releva les yeux et le trouva en train de la regarder.`],
[`tiret`,`— J'ai été couturière, dit-elle. Onze ans. Pour un magasin de vêtements en ville, un grand.`],
[`tiret`,`— Ça se voit.`],
[`tiret`,`— C'est ce qu'on me dit.`],
[`tiret`,`— Julie s'est proposée pour reprendre toutes les affaires d'Eliott, dit June depuis l'évier. Entre les allers-retours en ville et le reste, ça me fait ça en moins à m'occuper.`],
[`p`,`Julie haussa une épaule et lui rendit son sourire.`],
[`pause`,`· · ·`],
[`tiret`,`— Paul s'en va, dit June. Trois semaines. Ou quatre, ça dépendra de la place.`],
[`tiret`,`— Il est content d'aller au jardin ?`],
[`tiret`,`— Il compte les jours à l'envers depuis un mois. Il a refait son sac deux fois, et il l'a défait deux fois pour vérifier qu'il avait bien tout mis. Je le laisse faire, ça l'occupe.`],
[`tiret`,`— Et vous ?`],
[`tiret`,`— Moi, c'est le quatrième. On s'y fait.`],
[`p`,`Elle passa une assiette sous l'eau et la posa sur la pile sans la lâcher tout de suite.`],
[`tiret`,`— Enfin, c'est ce qu'on dit.`],
[`pause`,`· · ·`],
[`tiret`,`— Lui, c'est autre chose, reprit-elle. Je ne dirais pas que c'est de pire en pire. Mais il ne me raconte plus rien. Il rentre, il monte, il redescend pour manger. Je lui pose une question, il me répond juste ce qu'il faut pour que j'arrête d'en poser.`],
[`tiret`,`— Il dort ?`],
[`tiret`,`— Il dort. C'est déjà ça.`],
[`p`,`Elle chercha son torchon, le trouva sur son épaule, et s'essuya les mains avec.`],
[`tiret`,`— Il vous parle, à vous.`],
[`p`,`Elle dit ça comme on dit qu'il va pleuvoir, et elle passa à autre chose.`],
[`pause`,`· · ·`],
[`p`,`L'escalier fit du bruit. Eliott descendit les dernières marches d'un coup et s'arrêta en bas, une main sur la rampe.`],
[`tiret`,`— Vous êtes venu.`],
[`tiret`,`— J'ai dit que je viendrais.`],
[`p`,`Il avait des affaires à lui, maintenant. Une chemise trop large aux épaules, un pantalon repris à la taille, des chaussures que personne n'avait encore usées.`],
[`p`,`Son visage était doux, encore rond aux joues, avec un nez court et droit et une bouche fine. Quelqu'un qui savait le faire lui avait coupé les cheveux, et ils repartaient quand même en mèches sur le front et sur les oreilles. Ce qui tenait le visage, c'étaient les yeux. Verts, larges, et ils prenaient toute la place.`],
[`p`,`Le reste était mince sans être maigre. Épaules étroites, poignets étroits, des mains encore petites. Il y avait dans sa façon de se tenir quelque chose qui cherchait encore sa forme.`],
[`p`,`Julie posa son ouvrage et se leva pour lui tirer sur le bas de la chemise, des deux côtés, jusqu'à ce que ça tombe droit.`],
[`tiret`,`— Voilà. Comme ça tu es beau.`],
[`tiret`,`— Arrête.`],
[`p`,`Il se laissa faire jusqu'au bout, et il attendit qu'elle ait fini pour reculer.`],
[`pause`,`· · ·`],
[`tiret`,`— On sort ?`],
[`p`,`Eliott regarda June, qui lui montra la porte avec le menton.`],
[`tiret`,`— On va où ?`],
[`tiret`,`— Tu verras.`],
[`tiret`,`— Je déteste quand vous dites ça.`],
[`p`,`Il s'assit par terre dans le couloir pour mettre ses chaussures, et il y mit plus de temps qu'il n'en fallait. June rouvrit la porte pour eux et la tint jusqu'à ce qu'ils soient dehors tous les deux.`],

  ],
  tenu: [
`<strong>La visite montrée n'est pas la première, et rien ne le dit.</strong> <em>June ouvre sans s'étonner, elle appelle Eliott, elle repart vers sa cuisine.</em> Aucune phrase ne justifie la venue d'Andrew — ni du narrateur, ni de lui, ni d'elle.`,
`<strong>Le chapitre s'ouvre sur ce qu'il n'a pas fait.</strong> <em>La case d'observations du prologue est restée vide, la ligne est partie aux archives, et personne ne la lui a réclamée.</em> Le manque est posé avant les présentations.`,
`<strong>Julie porte l'inversion des âges, et personne ne l'explique.</strong> <em>Elle a dix ans, elle réparait des toits, et elle est chez elle.</em> Eliott bute dessus en trois répliques, Andrew répond deux mots, et on passe.`,
`<strong>Paul entre par une phrase et n'apparaît pas.</strong> <em>Il compte les jours à l'envers depuis un mois.</em> Ce qu'est une entrée au jardin n'est pas décrit : l'épilogue est là pour ça.`
  ],
  ouvre: [
`<strong>Le titre.</strong> <em>L'aquarium suit la forme des deux autres, qui nomment un lieu — mais il dit peut-être trop tôt où ils vont.</em>`,
`<strong>Le portrait d'Eliott tient en un bloc, à la descente de l'escalier.</strong> <em>S'il arrête le chapitre, le corps peut repartir dehors, en marchant, et ne laisser ici que le visage.</em>`,
`<strong>Combien de lieux du rituel sont montrés.</strong> <em>L'aquarium occupe déjà tout l'aller ; un second ferait visite guidée.</em>`
  ],
  note: `⚠️ <strong>Premier jet du premier mouvement, 22 août 2026.</strong> <em>La maison, jusqu'à la sortie.</em> <strong>La suite — l'aquarium, puis l'école au retour — vient après ta lecture.</strong>

<strong>Le titre est provisoire.</strong> <em>Il suit la forme des deux autres, qui nomment un lieu ; s'il en dit trop tôt sur la sortie, il saute.</em>`
},

{
  id: `epilogue`,
  rang: `Épilogue`,
  titre: `Épilogue`,
  scene: `jardin-fin`,
  sous: `Le jour de l'entrée au jardin · point de vue d'Andrew · écrit avec l'autrice le 16 août 2026`,
  p: [

[`p`,`Il n'y avait aucun endroit où se mettre.`],
[`p`,`Andrew s'en aperçut en arrivant, et il aurait dû s'en douter. Plus près, il faisait partie d'un groupe auquel il n'appartenait pas. Plus loin, il regardait. Il finit par s'adosser à un arbre, à une trentaine de mètres, et ne sut pas quoi faire de ses mains.`],
[`p`,`Les groupes attendaient devant la grille, en petits paquets qui s'étaient formés tout seuls le long de l'enceinte. Chaque groupe avait ses berceurs : parfois un berceur pour un arrivant, parfois trois arrivants pour un berceur et parfois plus.`],
[`p`,`Les petits, eux, se regardaient. Deux avaient déjà commencé à se courir après en riant, en tournant autour d'un berceur qui ne bougeait pas. Un troisième faisait le tour d'un groupe voisin par l'extérieur, l'air de rien, en cherchant une ouverture. Un quatrième ne lâchait pas la jupe de sa berceuse et fixait le mur.`],
[`p`,`Les berceurs, entre confrères et consœurs, tenaient des conversations animées. Il était question de la construction du nouveau centre commercial, d'un collègue ayant changé de section, de petits potins de quartier. Ils faisaient ça tous les ans.`],
[`p`,`Une femme, un peu à l'écart, ne participait pas. Elle avait gardé la main sur l'épaule du sien.`],
[`p`,`June était tout au bout, contre la grille. Six ans qu'il ne l'avait pas vue.`],
[`p`,`Il la retrouva plus jeune qu'il ne l'avait laissée. Rien d'autre n'avait bougé : elle tenait Eliott par l'épaule, sans le serrer, de la main dont on tient quelqu'un qui va partir mais pas tout de suite. Une autre berceuse se tenait avec eux, et June lui parlait déjà. Le petit, lui, se tenait sur la pointe des pieds. Il essayait de voir à travers les barreaux, et ce qu'il y avait derrière ne se voyait pas d'ici.`],
[`p`,`Elle leva la tête et le vit. Elle n'eut pas l'air surprise — elle devait s'y attendre — mais son visage se détendit un peu, et elle fit un petit mouvement du menton, deux centimètres, qui voulait dire viens.`],
[`p`,`Il compta les petits en traversant. Ils étaient quarante-deux.`],
[`p`,`Il les rejoignit. Eliott leva la tête, lui dit bonjour, et retourna à ses barreaux. Andrew se mit à côté d'eux, à la bonne distance : celle d'un homme qui n'a rien à faire là et qui est venu quand même.`],
[`p`,`La grille s'ouvrit à l'heure. Il n'y eut ni annonce ni discours : deux battants qu'on tira vers l'intérieur, et un homme qui sortit d'un pas, suivi de cinq berceurs qui se répartirent le long de la file sans qu'on ait à leur dire où aller. Il en connaissait plusieurs et les salua par leur prénom.`],
[`p`,`Sept ou huit petits pour un berceur, c'était la norme de l'administration. Dans les faits ça ne tombait jamais juste : les plus jeunes étaient presque tous pris au cas par cas, et ceux de sept et huit ans formaient des groupes plus gros. Andrew fit le calcul avant d'y penser. Le compte tombait juste.`],
[`p`,`Les groupes se mirent en mouvement. Ça se fit sans ordre et sans bousculade, à la vitesse à laquelle des gens qui se connaissent se laissent passer les uns les autres. Des petits se retournèrent, deux ou trois s'accrochèrent, on les décrocha doucement.`],
[`p`,`Une berceuse s'accroupit, toute souriante, devant l'un d'entre eux qui hésitait, et lui prit les deux mains.`],
[`tiret`,`— Eh bien dis donc ! On t'attendait, toi.`],
[`p`,`La plupart entrèrent sans regarder derrière eux. Un petit se retourna pour vérifier qu'on le regardait, constata que c'était le cas, et repartit en sautillant pour rattraper son groupe.`],
[`p`,`June ne bougea pas. Elle laissa la file s'écouler devant elle, puis elle se tourna vers sa consœur et lui parla à voix basse.`],
[`p`,`L'autre était agenouillée à hauteur d'Eliott et lui caressait les cheveux en écoutant. Elle regarda la grille, puis Andrew. Elle se tourna vers le responsable d'accueil, qui suivait la file de loin, et lui fit un signe. Il répondit par un autre, plus court, et les deux battants restèrent où ils étaient. Alors elle se releva et recula de quelques pas.`],
[`p`,`Andrew s'avança d'un pas. June ne le regarda pas tout de suite : elle avait les yeux sur le petit et elle vérifiait des choses qui n'avaient pas besoin de l'être.`],
[`tiret`,`— Tu as ton sac. La feuille est dans la poche de devant, tu ne la sors pas, c'est eux qui la demanderont.`],
[`tiret`,`— D'accord.`],
[`tiret`,`— Ils vont te montrer où tu dors, et après tu mangeras. Tu n'auras rien à demander à personne, ils viendront te chercher.`],
[`tiret`,`— Je sais.`],
[`tiret`,`— Je sais que tu sais.`],
[`p`,`Elle s'accroupit devant lui. Elle resta une seconde de trop dans cette position, une seule, et Andrew regarda ailleurs pendant cette seconde-là.`],
[`p`,`Puis elle lui prit les deux mains et lui dit la seule phrase qui n'était pas une consigne.`],
[`tiret`,`— Tu vas être bien là-dedans. Mieux qu'avec moi.`],
[`p`,`Eliott ne répondit pas. Il n'y avait rien à répondre à ça, et surtout il n'écoutait plus vraiment : derrière la grille, il y avait des petits pas précipités et des murmures enjoués ; c'était plus fort que lui.`],
[`p`,`Elle se releva, lissa le devant de sa veste d'un geste qui ne servait à rien, et se tourna vers Andrew.`],
[`tiret`,`— Merci d'être venu.`],
[`tiret`,`— C'est normal.`],
[`p`,`Elle eut un petit sourire qui n'était pas vraiment pour lui, puis elle passa la lanière de son sac sur son épaule et s'en alla.`],
[`p`,`Elle avait dit ce qu'elle avait à dire et elle l'avait dit vite. S'attarder, lui laisser une chance de répondre, ça aurait voulu dire rester — et elle n'aurait plus su repartir ensuite. Andrew regarda sa silhouette se fondre entre les arbres. Elle ne se retourna pas.`],
[`p`,`Eliott aussi l'observa une bonne minute, silencieux.`],
[`tiret`,`— T'inquiète pas. Elle viendra te voir, tu la connais.`],
[`p`,`Il hocha la tête sans quitter les arbres des yeux.`],
[`p`,`Peu à peu, l'allée se vida. Les berceurs repartaient à leurs occupations, seuls ou à deux, et le bruit de leurs conversations s'éloigna vers le bout de la rue.`],
[`p`,`Qu'est-ce qu'on pouvait faire, dans ces cas-là ? Andrew ne savait pas s'il fallait dire quelque chose, ou si le silence faisait partie de ce qu'on offrait. Il regardait le bout de ses chaussures et il attendait, comme on attend un train dont on n'a pas l'horaire.`],
[`p`,`La femme qui prenait la suite s'était éloignée de quelques pas — assez pour laisser de la place, pas assez pour disparaître.`],
[`p`,`Eliott s'assit sur un banc de pierre non loin d'eux, encore froid de la nuit. Il regardait droit devant lui, quelque part dans ses pensées. Andrew l'observa un moment, puis il vint s'asseoir à côté de lui et regarda dans la même direction. Deux moineaux se disputaient une miette d'on ne sait quoi, au milieu de l'allée, inconscients d'être épiés par deux parfaits inconnus.`],
[`p`,`Ce fut Eliott qui parla.`],
[`tiret`,`— Merci.`],
[`p`,`Andrew leva la tête.`],
[`tiret`,`— De quoi ?`],
[`tiret`,`— De rien. De tout. On m'a parlé de ce jardin et j'avais tellement envie de le voir de mes propres yeux… mais elle… elle voulait pas. Elle voulait plus, et je sais pas pourquoi. Pourtant ça a l'air beau.`],
[`p`,`Il hésita.`],
[`tiret`,`— Il lui est arrivé quoi, tu crois ?`],
[`tiret`,`— J'en sais trop rien.`],
[`p`,`C'était vrai. Personne ne le lui avait dit à lui non plus.`],
[`p`,`Eliott pencha légèrement la tête, l'oreille tendue. De l'autre côté de l'enceinte, des cris et des rires montaient par vagues, se rapprochaient, s'éloignaient. Il y avait le bruissement des feuilles, des chants quelque part, et sous les chants le ronflement d'une tondeuse. L'odeur de l'herbe coupée arrivait jusqu'à eux. Eliott inspira longuement, comme on savoure. Il balançait toujours ses jambes sous le banc. Elles ne touchaient pas le sol, et elles n'en prenaient pas le chemin.`],
[`p`,`Puis il ajouta, plus bas, comme s'il s'agissait d'une chose d'un autre ordre :`],
[`tiret`,`— … Et de m'avoir cru.`],
[`p`,`Andrew ne répondit pas. Il y avait une réponse quelque part, il la chercha deux ou trois secondes, et elle ne vint pas.`],
[`p`,`Le silence dura. Il n'avait rien de gêné.`],
[`tiret`,`— Toi, tu n'as jamais eu cette impression ?`],
[`p`,`Andrew sut immédiatement où la question l'amenait.`],
[`tiret`,`— De rêver en plein jour ?`],
[`p`,`Eliott plongea son regard dans celui du quadragénaire. Andrew fit non de la tête. C'était vrai et ce n'était pas vrai, et il n'avait pas de mot pour le milieu.`],
[`tiret`,`— Le premier, c'était le jour de ma cérémonie.`],
[`p`,`Il ne baissa pas la voix. Il en parlait comme d'une chose survenue à quelqu'un qu'il connaissait bien.`],
[`tiret`,`— Le monsieur à côté de moi. Je l'avais pas vu, au début. Je crois que lui non plus. J'ai vu tous les autres avant lui. Et quand je me suis tourné, j'ai vu ses yeux. Tout pareils que les miens. Je les ai regardés, et c'est comme si j'étais plus là. J'étais dehors. Pas dans la ruche. Dehors, dans un endroit que je connais pas. Il faisait froid comme il fait froid ici le matin, sauf que c'était pas ici.`],
[`p`,`Andrew écoutait sans bouger. Il ne relevait rien, il ne demandait pas de précision, il ne notait rien. Il ne cherchait pas à remettre les morceaux dans un ordre qui aurait tenu debout — il avait passé des semaines à faire exactement ça, et ça n'avait servi à rien.`],
[`p`,`Eliott poursuivit, le regard perdu dans le vague, comme s'il revoyait la scène à mesure qu'il la décrivait.`],
[`tiret`,`— Quelqu'un m'aidait à mettre un sac sur le dos. Un gros ! On aurait pu ranger la maison entière dedans.`],
[`p`,`Il rit tout seul.`],
[`tiret`,`— Il tirait sur les bretelles pour que ça tienne bien, et il a tapé deux fois dessus quand ça a été bon.`],
[`p`,`Il fit le geste. Deux petites tapes dans le vide, à hauteur de son épaule.`],
[`tiret`,`— C'était lui. Le monsieur d'à côté.`],
[`p`,`Et il repartit, plus vite, comme si tout lui revenait en même temps et qu'il fallait le dire avant que ça s'en aille. Sur le sac, un imperméable pendouillait à un mousqueton d'un côté, une gourde dépassait d'une poche de l'autre. Et dedans, il y avait une corde. Noire et orange. Très solide et très longue.`],
[`tiret`,`— C'est moi qui la portais ! C'est lui qui l'avait dit.`],
[`p`,`Il changea de voix sans s'en rendre compte, la fit plus grave, beaucoup trop grave :`],
[`tiret`,`— <em>C'est toi qui porteras la corde.</em>`],
[`p`,`Il trouvait ça drôle.`],
[`tiret`,`— Je me revois la tendre entre deux arbres, pour la tente.`],
[`p`,`Puis, sans transition :`],
[`tiret`,`— Et avant de partir, une dame m'a embrassé sur le front.`],
[`p`,`Il se balançait déjà, le buste de droite à gauche, la tête suivant le mouvement avec un temps de retard. Les yeux fermés, un large sourire sur le visage.`],
[`tiret`,`— Ce monsieur… j'avais l'impression de le connaître depuis toujours, alors que je l'avais jamais vu. Et puis c'est parti dans tous les sens. Lui, il me tendait la main. Il la tendait fort, tu vois, avec tout le bras. Moi j'arrivais pas à l'attraper. Nos mains glissaient trop.`],
[`tiret`,`— Glissaient trop ?`],
[`p`,`Ce fut la seule question qu'Andrew posa, et il la regretta aussitôt : elle n'appelait pas de réponse, elle demandait seulement qu'on répète.`],
[`p`,`Eliott ne répéta pas. Il naviguait dans ses souvenirs comme dans un trop-plein, et ce qui sortait de sa tête n'en sortait pas trié. Il n'y avait ni avant ni après, ni grand ni petit : tout venait dans le même souffle. Il rattachait les morceaux les uns aux autres comme un élève qui déverse tout sur sa copie, sans plan, de peur d'en oublier un en route.`],
[`tiret`,`— J'ai senti le sol s'en aller sous mes pieds alors que je bougeais même pas. Je bougeais même pas, je te jure. J'étais assis. Et le sol est parti ! J'avais les yeux ouverts et j'avais de l'eau dans la bouche.`],
[`p`,`Andrew ne bougea pas. Quelque part le long de l'enceinte, une grille se referma.`],
[`tiret`,`— J'ai jamais vu de rivière. Je savais même pas ce que c'était, un courant — on me l'a appris à l'école, cette année. Et pourtant j'ai rêvé que je tombais dedans.`],
[`p`,`Il dit ça avec un petit haussement d'épaules, un peu vexé, comme quelqu'un qui vient d'apporter lui-même la preuve qu'il a tort.`],
[`tiret`,`— Et j'avais peur. Pas juste pour moi. J'avais peur pour lui aussi, et je sais pas pourquoi.`],
[`p`,`Il se tut, puis reprit d'une voix différente, plus légère, comme s'il passait à quelque chose de plus agréable — et c'était exactement ce qu'il faisait.`],
[`tiret`,`— Il n'y a pas que ça, hein. Il y a une odeur, aussi. Je sais pas de quoi… De la fraise. De la chantilly. Et un petit côté fumé, juste par-dessus.`],
[`p`,`Il s'arrêta net. Puis il se tourna vers Andrew, les yeux pétillants, avec la tête de quelqu'un qui vient de trouver la réponse avant tout le monde.`],
[`tiret`,`— Comme un anniversaire !`],
[`p`,`Il en rit presque, et répéta le mot pour lui-même, content de l'avoir attrapé. Puis il repartit du même souffle :`],
[`tiret`,`— Et il y a un regard. Quelqu'un qui me regarde. C'est tout, il fait rien d'autre, il me regarde. Mais quand je me souviens de ça, je suis bien.`],
[`p`,`La femme qui attendait plus loin consulta quelque chose, tandis qu'un berceur remontait l'allée dans l'autre sens avec deux petits revenant de quelque part.`],
[`p`,`Les moineaux s'envolèrent subitement ; Andrew les perdit de vue.`],
[`tiret`,`— Et maintenant, je fais quoi avec ça ?`],
[`p`,`Il avait posé ça comme on pose une question de mathématiques : sérieusement, en attendant une méthode.`],
[`tiret`,`— Tu crois qu'ils vont se moquer de moi ici aussi ?`],
[`p`,`Andrew ouvrit la bouche. Il n'avait rien.`],
[`tiret`,`— Est-ce que tu viendras me voir ?`],
[`p`,`Le veilleur mit du temps. Il regarda l'allée, l'enceinte, la grille restée ouverte au bout.`],
[`tiret`,`— J'ai connu quelqu'un qui se posait beaucoup de questions, lui aussi.`],
[`p`,`Il dit ça comme on constate. Ça lui était venu tout seul, et il ne s'étonna pas de l'avoir dit.`],
[`tiret`,`— Il s'appelait comment ?`],
[`p`,`Près de la grille, la femme fit un pas et s'arrêta, les mains devant elle. Elle attendait comme on attend au fond d'une pièce où deux personnes ont quelque chose à finir.`],
[`tiret`,`— Je viendrai te voir.`],
[`p`,`Eliott hocha la tête. Il resta un moment les mains sur les genoux, puis il descendit du banc d'un petit bond. Les moineaux ne devaient pas être loin ; il fit deux pas dans l'allée pour les retrouver.`],
[`p`,`Il n'était plus question de la miette. Ils tournaient l'un autour de l'autre, les petits becs se frôlant, dans de courts gazouillis.`],
[`p`,`Il les regarda un moment. Sa respiration lente, presque suspendue.`],
[`tiret`,`— Il m'aimait beaucoup, tu sais.`],
[`p`,`Et parce que c'était là qu'il était depuis le début, Andrew continua de regarder en silence ce petit homme parler de son monsieur.`],
[`p`,`La femme s'était rapprochée. Elle ne dit rien : elle tendit la main, et elle souriait comme on sourit à quelqu'un qu'on va emmener voir quelque chose. Eliott lui donna la main sans hésiter.`],
[`tiret`,`— Un sentiment fort. Très fort. J'avais l'impression que lui c'était moi et que moi c'était lui.`],
[`p`,`Il tourna la tête, juste assez pour qu'Andrew attrape son profil. Il marqua une toute petite pause, la dernière, et détacha chacun de ses mots, un sourire empli d'une nostalgie nouvelle :`],
[`tiret`,`— Comme si je l'aimais encore plus fort que lui.`],
[`p`,`Andrew les regarda s'éloigner, la main du petit dans celle de la femme. Ils passèrent la grille sans se retourner, et quelqu'un la tira derrière eux.`],
[`p`,`Il resta assis. De l'autre côté du mur, les cris continuaient exactement comme avant.`],
[`p`,`Le banc n'était plus froid.`]

  ],
  tenu: [
`<strong>L'homme est entièrement là et jamais nommé.</strong> <em>Ses yeux, tout pareils que les miens</em> fait tout le travail, et personne ne le relève. Aucun mot de parenté n'apparaît : le petit ne les a jamais eus, il ne peut donc pas sentir qu'ils lui manquent.`,
`<strong>Et l'homme parle une fois.</strong> <em>C'est toi qui portes la corde</em> — cinq mots, rapportés par quelqu'un qui en est fier, six cents pages après le début. C'est tout ce qu'on aura jamais de lui.`,
`<strong>Ce ne sont pas les fragments d'un accident, ce sont ceux d'une vie.</strong> La corde, la tente, le baiser sur le front, la fraise et la chantilly, le regard. Le petit n'est pas traîné par un souvenir : il en a un plein sac, et il en sort les plus beaux.`,
`<strong>Il donne lui-même l'argument contre lui</strong> — il n'a jamais vu de rivière, on lui a appris le mot cette année. La vérité reste invérifiable parce que c'est lui qui la démonte.`,
`<strong>Le registre est celui d'une rentrée, et c'est ce qui empêche la fin d'être triste.</strong> On ne pleure pas à une rentrée : on a le ventre serré et on y va. Aucun pathos, aucune pitié, personne qui s'attarde.`,
`<strong>Andrew n'a jamais su s'autoriser à être là.</strong> Six ans plus tard il est encore à trente mètres, à vérifier de loin que le petit rentre bien — et c'est elle qui doit lui faire signe d'approcher. Le livre ne le dira jamais.`,
`<strong>Il compte les têtes, puis il vérifie le ratio des berceurs.</strong> C'est l'homme du registre une dernière fois, à vide, le jour où ça n'a plus aucune importance. Et la scène suivante, c'est un gamin qui le remercie de l'avoir cru.`,
`<strong>Personne ne traduit et personne ne comprend.</strong> Andrew dit quinze mots dans tout le tête à tête, dont une question qu'il regrette aussitôt.`,
`<strong>La question du nom reste sans réponse, et rien ne le signale.</strong> Il ne se dérobe pas : il répond à l'autre question, celle qui compte pour le petit. Le trou passe inaperçu de tout le monde sauf du lecteur.`,
`<strong>Il sait tout, et l'interdit ne porte que sur le prénom.</strong> <em>Il a compris à sa propre mort, et la salle du registre le lui a confirmé : il s'appelait Joël.</em> <strong>Donc « j'ai connu quelqu'un qui se posait beaucoup de questions, lui aussi » est une discrétion, pas un faux-raccord involontaire</strong> — il parle de lui et il choisit de ne pas le dire. <em>Et la question de l'enfant reste sans réponse pour la même raison : répondre voudrait dire expliquer, et ce n'est pas le jour.</em>`,
`<strong>Aucune résonance chez Andrew pour autant.</strong> <em>Non parce qu'il ignore — il sait — mais parce que c'est réglé depuis six ans.</em> Son arc s'est fermé au chapitre du registre ; celui-ci appartient au garçon. <strong>Sa phrase lui vient toute seule et il ne s'étonne pas de l'avoir dite, comme on ne s'étonne pas d'une chose qu'on a fini de porter.</strong>`,
`<strong>Ce qu'il ne sait toujours pas, en revanche :</strong> qui était l'homme assis à côté d'Eliott à sa cérémonie. <em>C'est le garçon qui le lui donne, ici, sans savoir ce qu'il donne</em> — et c'est la seule chose que quelqu'un offre à Andrew dans tout le livre.`,
`<strong>Il est déjà parti quand il finit sa phrase.</strong> Il a donné sa main à quelqu'un d'autre et il termine par-dessus son épaule.`,
`<strong>Ce chapitre est aussi la fin que Joël n'a pas eue.</strong> <em>Lecture de l'autrice, 17 août 2026 : « il aurait été comme ça si le cas des jumelles avait fini autrement ».</em> Andrew sur ce banc, humble, un peu à côté, venu sans qu'on le lui demande — <strong>c'est l'homme que l'autre serait devenu s'il avait retrouvé les siennes.</strong> C'est le seul endroit du livre où l'on voit l'après d'une affaire qui finit bien, et l'autre n'en a jamais eu.`,
`<strong>Conséquence : rien dans le chapitre ne doit y pointer.</strong> <em>La phrase « j'ai connu quelqu'un qui se posait beaucoup de questions, lui aussi » suffit — et elle ne suffit que parce qu'elle ne sait pas ce qu'elle dit.</em> Le lecteur qui a compris voit Joël assis sur ce banc. Celui qui n'a pas compris voit un homme fatigué qui a tenu parole.`,
`<strong>Et la tristesse se pose sur celui qui reste.</strong> Elle n'a pas le droit d'aller sur Eliott — il entre dans l'insouciance, c'est le meilleur qui pouvait lui arriver. Alors elle va à l'homme resté dehors, et elle s'y pose sans qu'un seul mot nomme un sentiment. <em>Le banc n'était plus froid</em> dit combien de temps il est resté là, et rien d'autre.`,
`<strong>Trois fils se referment en trois phrases.</strong> La grille, maintenue ouverte pour eux, se referme ; les cris de l'autre côté continuent exactement comme avant, parce que le monde ne s'est aperçu de rien ; et le banc, <em>encore froid de la nuit</em> quatre-vingt-dix paragraphes plus tôt, ne l'est plus.`,
`<strong>Ce que dit la dernière ligne, et il ne faut pas la « clarifier ».</strong> Le banc n'a pas gardé la chaleur d'un corps : il a gardé celle de ce qui s'y est dit. <em>Le petit y a vidé son sac — l'eau, la corde, le baiser, l'odeur d'anniversaire — et il repart sans.</em> La pierre était froide et dure le matin ; elle ne l'est plus. Ce n'est pas une trace de lui, c'est ce qu'il a déposé.`,
`<strong>Et la tournure négative fait tout le travail.</strong> <em>La place était encore chaude</em> serait une consolation qu'on ajoute ; <em>n'était plus froid</em> ne donne rien, ça retire seulement quelque chose. Rien n'est gagné — c'est juste un peu moins dur qu'au début de la journée. <em>Le seul pas du livre vers le réconfort, et il se fait par soustraction.</em>`,
`<strong>Ça referme le thème, pas seulement la scène.</strong> Tout le roman traite les voiles comme un fardeau, jusqu'à <em>et maintenant, je fais quoi avec ça ?</em> — auquel personne ne répond. La dernière ligne répond sans formuler : <strong>ce qu'il portait n'était pas que mauvais.</strong> Il y avait une corde dont il était fier, une dame qui l'embrassait sur le front, une odeur de gâteau.`,
`<strong>Le banc de pierre du matin n'est donc pas du décor.</strong> <em>Encore froid de la nuit</em> à la première moitié du chapitre : c'est l'endroit où il posera ce qu'il portait, et il faut qu'il soit dur et froid quand il s'y assoit.`
  ],
  ouvre: [
`⚠️ <strong>LE CHANTIER DE DEMAIN — le chapitre sonne trop triste.</strong> <em>Relecture de l'autrice, 17 août 2026 : « on dirait qu'ils partent vers la mort. Ce qui est vrai, mais il ne faudrait pas que ça se ressente comme ça. C'est un accompagnement de fin de vie. »</em> Le registre demandé au départ — une rentrée scolaire — s'est perdu à l'écriture.`,
`<strong>La correction en une phrase :</strong> la tristesse doit être celle d'Andrew seul, jamais celle de la scène. <em>Tous les autres sont soit au travail, soit contents d'y aller.</em> Il est le seul pour qui c'est une perte, et personne autour de lui ne partage ça.`,
`✅ <strong>Et le jardin n'est pas fermé, ce qui change le ton à lui seul.</strong> <em>On croise des petits et leur berceur dans la rue comme on croise ici une personne âgée au bras d'un soignant ; des équipes entrent pour l'entretien, d'autres livrent les repas.</em> <strong>Le mur n'est pas une frontière, c'est une adresse.</strong> — Piste : pendant qu'Andrew est sur le banc, un berceur remonte l'allée avec deux petits qui reviennent de quelque part. Deux lignes, et la scène cesse d'être un cimetière.`,
`✅ <strong>Et sa promesse est la seule qui aille dans le bon sens.</strong> <em>Eliott pourra aller voir June, qui habite à côté ; aller voir Andrew serait presque impensable — on ne croise pas de petits à la ruche, comme on ne croise pas de personnes âgées dans une maternité.</em> <strong>C'est donc à lui de se déplacer, et c'est ce qu'il fait sans qu'on le lui demande depuis six ans.</strong>`,
`<strong>Ce qu'il faut ajouter, point par point.</strong> ① <em>Les berceurs discutent de façon animée et légère</em> — c'est leur métier d'amener les petits ici, ils le font tous les ans ; la météo et la circulation dites « parce qu'on ne peut rien dire d'autre » sont à retourner. ② <em>Le pincement au cœur existe, mais tous ne le vivent pas pareil</em> — il en faut au moins un·e que ça ne remue pas. ③ <em>Le responsable et les berceurs d'accueil sont accueillants</em> : des sourires, des regards bienveillants, pas seulement des signes de tête administratifs. ④ <em>Eliott est heureux d'y aller</em> — inquiet, oui, mais curieux, pressé de voir ce qui se passe derrière. ⑤ <em>June peut dire sa réserve, mais la visite n'est pas fermée</em> : elle peut repasser, et ça change tout au ton de ses adieux.`,
`<strong>Les six endroits où la tristesse fuit, dans l'ordre du texte.</strong> ① les berceurs qui parlent « quand on ne peut rien dire d'autre » ; ② <em>elles ne touchaient pas le sol et elles ne le toucheraient plus</em> — la ligne la plus funèbre du chapitre, une pierre tombale ; ③ <em>ce qu'on puisse souhaiter à quelqu'un un jour pareil</em>, qui fait de l'entrée une épreuve ; ④ <em>mieux qu'avec moi</em>, qui sonne comme ce qu'on dit à un mourant ; ⑤ la sortie de June, qui est une sortie d'enterrement ; ⑥ aucun sourire nulle part chez le personnel.`,
`<strong>Et une question à calibrer :</strong> si June peut revenir, la promesse d'Andrew — <em>je viendrai te voir</em> — perd un peu de son poids. <em>À doser : elle enlève la finalité, ce qui est le but, mais elle ne doit pas rendre la sienne banale.</em>`,
`<strong>L'odeur.</strong> <em>La fraise, la chantilly, et un petit côté fumé par-dessus</em> — les bougies qu'on vient de souffler, et personne ne le dit. Elle ne doit jamais recouper celle des capsules — la formule de la capsule pourrie, forgée à la journée à la ruche.`,
`<strong>La réplique d'Andrew.</strong> <em>J'ai connu quelqu'un qui se posait beaucoup de questions, lui aussi</em> — les mots exacts restent à trouver. Ce qu'ils doivent porter : c'était survivable. Ce qu'ils ne doivent surtout pas porter : que ça s'est bien terminé.`,
`<strong>« Une nostalgie nouvelle »</strong> est le seul endroit où le narrateur pointe du doigt. C'est assumé, pour une dernière ligne. À relire une fois l'ensemble en place.`,
`<strong>Le chiffre d'arrivée de June.</strong> Il ne se dira jamais dans le texte, mais il faut le connaître pour savoir de combien elle a bougé en six ans — et ne pas la décrire deux fois de deux façons incompatibles.`,
`<strong>Ce chapitre n'a aucun filet.</strong> Tout repose sur le fait que le lecteur, lui, sait. Si le chapitre précédent ne l'a pas amené ici en sachant tout, la seconde moitié devient un gamin qui raconte des rêves. <em>Le réglage ne se fait pas ici — il se fait avant.</em>`,
`<strong>La description de l'enceinte appartient à la scène 14 b.</strong> Ici on n'en voit que ce qui passe par une grille ouverte, et le mur ne se décrit pas une seconde fois.`
  ],
  note: `🔒 <strong>VERROUILLÉ — validé par l'autrice le 20 août 2026.</strong> <em>Ce texte ne bouge plus, sauf demande explicite de sa part.</em> <strong>La fabrication de l'atelier vérifie son empreinte et refuse de tourner s'il a changé.</strong>

Écrit avec l'autrice le 16 août 2026, en une vingtaine de passes. <strong>Une rentrée scolaire, puis un monologue où le seul qui parle a huit ans.</strong> <em>Andrew ne comprend rien de ce qu'on lui raconte ; le lecteur comprend tout et n'a personne à qui le dire.</em>`
}];
